### ISSUE TITLE
Cannot unzip files on Windows due to UAC rules

### ISSUE THREAD

**Issue by asmundskalevik** [electron/electron-packager#1024]
ENOENT: no such file or directory, rename 'C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64\electron.exe' -> 'C:\Users\<user>\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64\stox.exe'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stox@1.0.0 package-win: `electron-packager . <appname> --platform win32 --arch x64 --out dist/ --overwrite`
npm ERR! Exit status 1
npm ERR!

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Operating System (Platform and Version) e.g. macOS 10.13.6 / Windows 10 (1803) / Ubuntu 18.04 x64

* Last Known Working Electron Packager version (if applicable) e.g. 11.0.0

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What does your `package.json` file look like?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by asmundskalevik** [comment]
using electron packager 14.0.0, than it crashed. had to downgrade to 13.1.1 then it worked fine. thanks
package
  "main": "index.js",
  "scripts": {
    "start": "electron .",
    "package-win": "electron-packager . stox --platform win32 --arch x64 --out dist/ --overwrite  --asar",

**Comment by malept** [comment]
Can you please provide the following information:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

**Comment by asmundskalevik** [comment]
ok,  i have added console output (Using cross-env and DEBUG for electron packager 13.1.1 and 14.0.0.9 It crashes in 14.0.0 when renaming the electron.exe. This seems to work o.k in 13.1.1

> cross-env DEBUG=electron-packager electron-packager . stox --platform win32 --arch x64 --out dist/ --overwrite  --asar

  electron-packager Electron Packager 13.1.1
  electron-packager Node v10.16.0
  electron-packager Host Operating system: win32 (x64) +0ms
  electron-packager Packager Options: {"_":[".","stox"],"deref-symlinks":true,"derefSymlinks":true,"download":{"strictSSL":true,"strict-ssl":true},"prune":true,"platform":"win32","arch":"x64","out":"dist/","overwrite":true,"asar":true,"dir":".","name":"stox","protocols":[]} +4ms
  electron-packager Target Platforms: win32 +1ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in E:\Projects\StoxProject\StoX\package.json +0ms
  electron-packager Inferring win32metadata.CompanyName from author in E:\Projects\StoxProject\StoX\package.json +1ms
  electron-packager Inferring target Electron version from electron in E:\Projects\StoxProject\StoX\package.json +4ms
  electron-packager Application name: stox +26ms
  electron-packager Target Electron version: 5.0.6 +1ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"strictSSL":true,"strict-ssl":true,"platform":"win32","arch":"x64","version":"5.0.6"} +0ms
  electron-packager Removing dist\stox-win32-x64 due to setting overwrite: true +341ms
Packaging app for platform win32 x64 using electron v5.0.6
  electron-packager Creating C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +90ms
  electron-packager Extracting C:\Users\aasmunds\AppData\Local\electron\Cache\electron-v5.0.6-win32-x64.zip to C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +2ms
  electron-packager Initializing app in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 from C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ 'E:\\Projects\\StoxProject\\StoX\\dist' ] +3s
  electron-packager Running asar with the options {} +1m
  electron-packager Renaming electron.exe to stox.exe in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 +29s
  electron-packager Running rcedit with the options {"version-string":{"FileDescription":"stox","InternalName":"stox","OriginalFilename":"stox.exe","ProductName":"stox","CompanyName":"IMR institute"},"file-version":"1.0.0","product-version":"1.0.0"} +0ms
  electron-packager Moving C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 to dist\stox-win32-x64 +2s
Wrote new app to dist\stox-win32-x64

> cross-env DEBUG=electron-packager electron-packager . stox --platform win32 --arch x64 --out dist/ --overwrite  --asar

  electron-packager Electron Packager 14.0.0
  electron-packager Node v10.16.0
  electron-packager Host Operating system: win32 (x64) +0ms
  electron-packager Packager Options: {"_":[".","stox"],"deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"platform":"win32","arch":"x64","out":"dist/","overwrite":true,"asar":true,"dir":".","name":"stox","protocols":[]} +4ms
  electron-packager Target Platforms: win32 +1ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in E:\Projects\StoxProject\StoX\package.json +0ms
  electron-packager Inferring win32metadata.CompanyName from author in E:\Projects\StoxProject\StoX\package.json +1ms
  electron-packager Inferring target Electron version from electron in E:\Projects\StoxProject\StoX\package.json +4ms
  electron-packager Application name: stox +23ms
  electron-packager Target Electron version: 5.0.6 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"win32","arch":"x64","version":"5.0.6","artifactName":"electron"} +0ms
  electron-packager Removing dist\stox-win32-x64 due to setting overwrite: true +10ms
Packaging app for platform win32 x64 using electron v5.0.6
  electron-packager Creating C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +140ms
  electron-packager Extracting C:\Users\aasmunds\AppData\Local\electron\Cache\electron-v5.0.6-win32-x64.zip to C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +3ms
  electron-packager Initializing app in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 from C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ 'E:\\Projects\\StoxProject\\StoX\\dist' ] +760ms
  electron-packager Running asar with the options {} +58s
  electron-packager Renaming electron.exe to stox.exe in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 +32s
ENOENT: no such file or directory, rename 'C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64\electron.exe' -> 'C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64\stox.exe'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! stox@1.0.0 package-win: `cross-env DEBUG=electron-packager electron-packager . stox --platform win32 --arch x64 --out dist/ --overwrite  --asar`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the stox@1.0.0 package-win script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\aasmunds\AppData\Roaming\npm-cache\_logs\2019-07-02T07_07_54_497Z-debug.log

**Comment by malept** [comment]
Exactly what version of Windows are you running?

**Comment by asmundskalevik** [comment]
$ cross-env DEBUG=electron-packager electron-packager . stox --overwrite --asar=true --platform=win32 --arch=x64 --out=release-builds --versi
on-string.CompanyName=HI --version-string.FileDescription=HI --version-string.ProductName="StoX"
WARNING: --asar does not take any arguments, it only has sub-properties (see --help)
  electron-packager Electron Packager 14.1.1
  electron-packager Node v10.16.0
  electron-packager Host Operating system: win32 10.0.17763 (x64) +0ms
  electron-packager Packager Options: {"_":[".","stox"],"overwrite":true,"asar":true,"platform":"win32","arch":"x64","out":"release-builds","version-string":{"CompanyName":"HI","FileDescription":"HI","ProductName":"StoX"},"versionString":{"companyName":"HI","fileDescription":"HI","productName":"StoX"},"deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"dir":".","name":"stox","protocols":[]} +2ms
  electron-packager Target Platforms: win32 +1ms
  electron-packager Target Architectures: x64 +1ms
  electron-packager Inferring appVersion from version in E:\Projects\TestApp\package.json +0ms
  electron-packager Inferring target Electron version from electron in E:\Projects\TestApp\package.json +3ms
  electron-packager Application name: stox +14ms
  electron-packager Target Electron version: 7.1.2 +1ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"win32","arch":"x64","version":"7.1.2","artifactName":"electron"} +0ms
  electron-packager Removing release-builds\stox-win32-x64 due to setting overwrite: true +9ms
Packaging app for platform win32 x64 using electron v7.1.2
  electron-packager Creating C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +25ms
  electron-packager Extracting C:\Users\aasmunds\AppData\Local\electron\Cache\httpsgithub.comelectronelectronreleasesdownloadv7.1.2electron-v7.1.2-win32-x64.zip\electron-v7.1.2-win32-x64.zip to C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +2ms
  electron-packager Initializing app in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 from C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ 'E:\\Projects\\TestApp\\release-builds' ] +751ms
  electron-packager Running asar with the options {} +129ms
  electron-packager Renaming electron.exe to stox.exe in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 +26msENOENT: no such file or directory, rename 'C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64\electron.exe' -> 'C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64\stox.exe'

**Comment by asmundskalevik** [comment]
The difference output between 13.1.1 and the latest 14 can be shown here:
electron-packager . stox --overwrite --asar=true --platform=win32 --arch=x64 --icon=assets/stox_icon.ico --out=release-builds --version-string.CompanyName=HI --version-string.FileDescription=HI --version-string.ProductName="StoX"

$ cross-env DEBUG=electron-packager electron-packager . stox --overwrite --asar=true --platform=win32 --arch=x64 --out=release-builds --versi
on-string.CompanyName=HI --version-string.FileDescription=HI --version-string.ProductName="StoX"
WARNING: --asar does not take any arguments, it only has sub-properties (see --help)
  electron-packager Electron Packager 13.1.1
  electron-packager Node v10.16.0
  electron-packager Host Operating system: win32 (x64) +0ms
  electron-packager Packager Options: {"_":[".","stox"],"deref-symlinks":true,"derefSymlinks":true,"download":{"strictSSL":true,"strict-ssl":true},"prune":true,"overwrite":true,"asar":true,"platform":"win32","arch":"x64","out":"release-builds","version-string":{"CompanyName":"HI","FileDescription":"HI","ProductName":"StoX"},"versionString":{"companyName":"HI","fileDescription":"HI","productName":"StoX"},"dir":".","name":"stox","protocols":[]} +1ms
  electron-packager Target Platforms: win32 +1ms
  electron-packager Target Architectures: x64 +1ms
  electron-packager Inferring appVersion from version in E:\Projects\TestApp\package.json +0ms
  electron-packager Inferring target Electron version from electron in E:\Projects\TestApp\package.json +4ms
  electron-packager Application name: stox +15ms
  electron-packager Target Electron version: 7.1.2 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"strictSSL":true,"strict-ssl":true,"platform":"win32","arch":"x64","version":"7.1.2"} +0ms
  electron-packager Removing release-builds\stox-win32-x64 due to setting overwrite: true +312ms
Packaging app for platform win32 x64 using electron v7.1.2
  electron-packager Creating C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +26ms
  electron-packager Extracting C:\Users\aasmunds\AppData\Local\electron\Cache\electron-v7.1.2-win32-x64.zip to C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +3ms
  electron-packager Initializing app in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 from C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ 'E:\\Projects\\TestApp\\release-builds' ] +2s
  electron-packager Running asar with the options {} +117ms
  electron-packager Renaming electron.exe to stox.exe in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 +31ms  electron-packager Running rcedit with the options {"version-string":{"FileDescription":"stox","InternalName":"stox","OriginalFilename":"stox.exe","ProductName":"stox"},"file-version":"1.0.0","product-version":"1.0.0"} +0ms
  electron-packager Moving C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 to release-builds\stox-win32-x64 +641ms
Wrote new app to release-builds\stox-win32-x64


$ cross-env DEBUG=electron-packager electron-packager . stox --overwrite --asar=true --platform=win32 --arch=x64 --out=release-builds --versi
on-string.CompanyName=HI --version-string.FileDescription=HI --version-string.ProductName="StoX"
WARNING: --asar does not take any arguments, it only has sub-properties (see --help)
  electron-packager Electron Packager 14.1.1
  electron-packager Node v10.16.0
  electron-packager Host Operating system: win32 10.0.17763 (x64) +0ms
  electron-packager Packager Options: {"_":[".","stox"],"overwrite":true,"asar":true,"platform":"win32","arch":"x64","out":"release-builds","version-string":{"CompanyName":"HI","FileDescription":"HI","ProductName":"StoX"},"versionString":{"companyName":"HI","fileDescription":"HI","productName":"StoX"},"deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"dir":".","name":"stox","protocols":[]} +2ms
  electron-packager Target Platforms: win32 +1ms
  electron-packager Target Architectures: x64 +1ms
  electron-packager Inferring appVersion from version in E:\Projects\TestApp\package.json +0ms
  electron-packager Inferring target Electron version from electron in E:\Projects\TestApp\package.json +3ms
  electron-packager Application name: stox +14ms
  electron-packager Target Electron version: 7.1.2 +1ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"win32","arch":"x64","version":"7.1.2","artifactName":"electron"} +0ms
  electron-packager Removing release-builds\stox-win32-x64 due to setting overwrite: true +9ms
Packaging app for platform win32 x64 using electron v7.1.2
  electron-packager Creating C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +25ms
  electron-packager Extracting C:\Users\aasmunds\AppData\Local\electron\Cache\httpsgithub.comelectronelectronreleasesdownloadv7.1.2electron-v7.1.2-win32-x64.zip\electron-v7.1.2-win32-x64.zip to C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +2ms
  electron-packager Initializing app in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 from C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ 'E:\\Projects\\TestApp\\release-builds' ] +751ms
  electron-packager Running asar with the options {} +129ms
  electron-packager Renaming electron.exe to stox.exe in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 +26msENOENT: no such file or directory, rename 'C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64\electron.exe' -> 'C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64\stox.exe'

**Comment by asmundskalevik** [comment]
$ electron-packager --version
Electron Packager 14.1.1
Node v10.16.0
Host Operating system: win32 10.0.17763 (x64)

**Comment by malept** [comment]
Can you run the following:

```
cross-env DEBUG=electron-packager,@electron/get* electron-packager . stox --platform win32 --arch x64 --out dist/ --overwrite  --asar
```

**Comment by asmundskalevik** [comment]
$ cross-env DEBUG=electron-packager,@electron/get* electron-packager . stox --platform win32 --arch x64 --out dist/ --overwrite  --asar
The result of this is the same, still cannot find or rename the electron.exe file:

  electron-packager Electron Packager 14.1.1
  electron-packager Node v10.16.0
  electron-packager Host Operating system: win32 10.0.17763 (x64) +0ms
  electron-packager Packager Options: {"_":[".","stox"],"platform":"win32","arch":"x64","out":"dist/","overwrite":true,"asar":true,"deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"dir":".","name":"stox","protocols":[]} +3ms
  electron-packager Target Platforms: win32 +0ms
  electron-packager Target Architectures: x64 +1ms
  electron-packager Inferring appVersion from version in E:\Projects\TestApp\package.json +0ms
  electron-packager Inferring target Electron version from electron in E:\Projects\TestApp\package.json +6ms
  electron-packager Application name: stox +22ms
  electron-packager Target Electron version: 7.1.2 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"win32","arch":"x64","version":"7.1.2","artifactName":"electron"} +0ms
  @electron/get:index Checking the cache for electron-v7.1.2-win32-x64.zip (https://github.com/electron/electron/releases/download/v7.1.2/electron-v7.1.2-win32-x64.zip) +0ms
  @electron/get:index Cache hit +7ms
Packaging app for platform win32 x64 using electron v7.1.2
  electron-packager Creating C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +18ms
  electron-packager Extracting C:\Users\aasmunds\AppData\Local\electron\Cache\httpsgithub.comelectronelectronreleasesdownloadv7.1.2electron-v7.1.2-win32-x64.zip\electron-v7.1.2-win32-x64.zip to C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template +2ms
  electron-packager Initializing app in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 from C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64-template template +0ms
  electron-packager Ignored paths based on the out param: [ 'E:\\Projects\\TestApp\\dist' ] +1s
  electron-packager Running asar with the options {} +331ms
  electron-packager Renaming electron.exe to stox.exe in C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64 +38msENOENT: no such file or directory, rename 'C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64\electron.exe' -> 'C:\Users\aasmunds\AppData\Local\Temp\electron-packager\win32-x64\stox-win32-x64\stox.exe'

**Comment by malept** [comment]
Can you open `C:\Users\aasmunds\AppData\Local\electron\Cache\httpsgithub.comelectronelectronreleasesdownloadv7.1.2electron-v7.1.2-win32-x64.zip\electron-v7.1.2-win32-x64.zip` and make sure it contains `electron.exe`?

**Comment by asmundskalevik** [comment]
yes, it does.

**Comment by malept** [comment]
Can you reproduce this on a different Windows 10 machine?

**Comment by asmundskalevik** [comment]
Yes, my colleague has reproduced this on his Windows 10 machine

**Comment by malept** [comment]
This does not happen in CI, so I'm very confused as to why this would happen. What sort of anti-malware, anti-virus, etc., sort of software is installed?

**Comment by asmundskalevik** [comment]
No, only UAC (user account control) is enabled by IT (forced) and Windows Defender. But the Event Viewer doesnt report about any app-errors when I build. Can you explain why version 13.1.1 works, but not version 14. Which changes was intoduced in version 14 that made it stop working?

**Comment by malept** [comment]
Per the [release notes](https://github.com/electron/electron-packager/releases/tag/v14.0.0), Packager uses Windows's built-in zip extraction to unzip files. The previous solution is no longer maintained and susceptible to security vulnerabilities.

**Comment by asmundskalevik** [comment]
But that's nor the reason? Or...

**Comment by asmundskalevik** [comment]
Hi. I resolved this by adding uac rules for allowing powershell scripts to be run.
Now it works, brilliant. Thank you...
