### ISSUE TITLE
Startup crash after packaging with Electron 6.0

### ISSUE THREAD

**Issue by PalmerAL** [electron/electron-packager#1032]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:** 14.0.2
  * 
* **Electron Version:** 6.0.0-beta.15
  * 
* **Operating System:** macOS 10.14.4
  * 
* **Last Known Working Electron Packager version:**:
  * 

When using the latest version of Electron-packager with Electron 5.0, everything works as expected, and I get a working app. However, after upgrading to Electron 6.0, the packaged app will crash on startup, even though it runs fine before it is packaged.

In particular, packaging with Electron 5.0 results in this set of items in `Contents/Frameworks`:
<img width="598" alt="Screen Shot 2019-07-23 at 11 17 57 PM" src="https://user-images.githubusercontent.com/10314059/61764849-3067ea80-ada0-11e9-9433-b917d4204dfc.png">

Packaging with Electron 6.0 results in a different set of frameworks:
<img width="593" alt="Screen Shot 2019-07-23 at 11 19 36 PM" src="https://user-images.githubusercontent.com/10314059/61764889-5b523e80-ada0-11e9-9f71-a3aca0cc19c8.png">

In both cases, the helper executable inherits the name of my app, which seems reasonable. However, what is interesting is that if I rename `Min Helper` to `Electron Helper`, and `Min Helper/Contents/MacOS/Min Helper` to `Electron Helper/Contents/MacOS/Electron Helper`, then the crash goes away, and the app runs normally.

So I think that in Electron 6.0, the helper app has to keep the "Electron" name, instead of using the name of the app. I don't really understand what changed in Electron to cause this, but perhaps you have an idea (and if this is an Electron bug, I'm happy to file an issue there as well).

**Comment by MarshallOfSound** [comment]
@PalmerAL I have context on this 👍 

> So I think that in Electron 6.0, the helper app has to keep the "Electron" name

I don't believe this is the case, will keep in mind when fixing though 👍

**Comment by MarshallOfSound** [comment]
Fixed in https://github.com/electron/electron-packager/pull/1033 @PalmerAL was as expected just not renaming the new helpers to your application name.

**Comment by PalmerAL** [comment]
Thanks for fixing this!
