### ISSUE TITLE
Add Option to Package App as a Standalone Executable

### ISSUE THREAD

**Issue by Lonniebiz** [electron/electron-packager#1034]
Please support packaging to a Standalone Executable.

This would add an additional layer of source code protection in conjunction with the `--asar` option and it will simplify launching the application; people could just download the app and run it without having to poke around hunting which file is the executable.

**Comment by malept** [comment]
This is outside the scope of Electron Packager, which only customizes the prebuilt Electron binary and optionally bundles the source code in the `asar` format. You want to create a [distributable file](https://github.com/electron/electron-packager#distributable-creators) (such as an installer) which is handled by other modules.

**Comment by Lonniebiz** [comment]
@malept :+1:  Thanks for the link.

Please help me with my terminology. What do you call what I'm looking for?

I'm not looking for an installer, I'm looking for something that produces one executable file, that does NOT "install" the electron app.

Instead, this single solitary file contains within it all dependencies needed to just simply launch the program upon double-clicking it the file.

**Comment by malept** [comment]
This is probably a "[portable app](https://en.wikipedia.org/wiki/Portable_application)", although by default, Electron apps write configuration to the user's config directory, as it's based on Chromium.
