### ISSUE TITLE
Electron-packager packages wrong version of project.

### ISSUE THREAD

**Issue by PlatypusIV** [electron/electron-packager#1040]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  "electron-packager": "^14.0.4"
* **Electron Version:**
  "electron": "^3.0.10"
* **Operating System:**
  Windows 10
* **Last Known Working Electron Packager version:**:
  "electron-packager": "^14.0.4"

### Expected Behavior
Get a .exe which contains everything ive worked on up until now.

### Actual Behavior
After packaging the application and booting it up, I see a that I have travelled back in time, to a version of my app that I worked on last week.

### Additional Information
My apologies as this might just be my own incompetence.
Every time I try to package the app im working on, I end up getting a build from several days ago.
Im not sure what im doing wrong, or why its packaging a past version of my project.
Any help would be appreciated.

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?
