### ISSUE TITLE
Mac App Store rejected upload with "ERROR ITMS-90261: Bad CFBundleExecutable..." in electron version >= 6

### ISSUE THREAD

**Issue by lesleyandreza** [electron/electron-packager#1045]
### Preflight Checklist

* [X] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [X] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 14.0.4
* **Electron Version:**
  * `>=6`
* **Xcode Version:**
  * 10.2
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron Packager version:**:
  * The current version of electron-packager 14.0.4 works with electron <= 5

### Expected Behavior
Succesfull upload with *Application Loader*

### Actual Behavior
The Application Loader shows the following error:
![image](https://user-images.githubusercontent.com/14945792/63891745-4a5aa580-c9bc-11e9-83e5-515359f5ee2a.png)

### To Reproduce

 - Build package with `electron-packager`
 - Sign the package with  `electron-osx-sign`
 - Generate the `pkg`  with `electron-osx-flat`
 - Use the aplication loader to upload the `pkg`
 - Choose options `mas` and `distribution`.

\* [Steps followed from this sign guide](https://mintkit.net/electron-userland/electron-osx-sign/guide/).

### Additional Information
These steps works the current version of electron-packager 14.0.4 works with electron <= 5

**Comment by malept** [comment]
What is the value of `CFBundleExecutable` in the `Info.plist` for the GPU helper? (Or really, any helper that's failing...)
