### ISSUE TITLE
Cannot download 6.0.9 prebuilt binary from taobao mirror

### ISSUE THREAD

**Issue by jxf114208** [electron/electron-packager#1050]
### Issue Details

* **Electron Packager Version:**
  * 14.0.6
* **Electron Version:**
  * 6.0.9
* **Operating System:**
  *  Ubuntu 18.04 x64
* **Last Known Working Electron Packager version:**:
  * 

### Expected Behavior
Can be packaged normally

### Actual Behavior
`jxf@jxf-MS-7586:~/git/testElectron$ electron-packager .`
`Response code 404 (Not Found)`

### To Reproduce
```
# Clone the repository
$ git clone https://github.com/electron/electron-quick-start
# Go into the repository
$ cd electron-quick-start
# Install dependencies
$ npm install
# package
$ electron-packager .
# Terminal out text
Response code 404 (Not Found)
```

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

**Comment by wenbingzhang** [comment]
➜  test electron-packager ./ myapp --out ../OutApp --electron-version=6.0.9
  electron-packager Electron Packager 14.0.6
  electron-packager Node v10.16.3
  electron-packager Host Operating system: darwin 16.7.0 (x64) +0ms
  electron-packager Packager Options: {"_":["./","myapp"],"deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"out":"../OutApp","electron-version":"6.0.9","electronVersion":"6.0.9","dir":"./","name":"myapp","protocols":[]} +2ms
  electron-packager Target Platforms: darwin +1ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring appVersion from version in /Users/bing/Downloads/test/package.json +0ms
  electron-packager Application name: myapp +9ms
  electron-packager Target Electron version: 6.0.9 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"darwin","arch":"x64","version":"6.0.9","artifactName":"electron"} +0ms
Response code 404 (Not Found)

**Comment by malept** [comment]
Can you re-run with `DEBUG='electron-packager,@electron/get:*'` ?

**Comment by wenbingzhang** [comment]
> 你可以重新参加`DEBUG='electron-packager,@electron/get:*'`吗？

  electron-packager Electron Packager 14.0.6
  electron-packager Node v10.16.3
  electron-packager Host Operating system: darwin 16.7.0 (x64) +0ms
  electron-packager Packager Options: {"_":["./"],"deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"electron-version":"6.0.9","electronVersion":"6.0.9","dir":"./","protocols":[]} +2ms
  electron-packager Target Platforms: darwin +0ms
  electron-packager Target Architectures: x64 +0ms
  electron-packager Inferring application name from name in /Users/xxxx/Documents/Project/Electron/xxxx/package.json +0ms
  electron-packager Inferring appVersion from version in /Users/xxxx/Documents/Project/Electron/xxxx/package.json +0ms
  electron-packager Application name: MxSrvs +9ms
  electron-packager Target Electron version: 6.0.9 +0ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"darwin","arch":"x64","version":"6.0.9","artifactName":"electron"} +0ms
  @electron/get:index Checking the cache for electron-v6.0.9-darwin-x64.zip (http://npm.taobao.org/mirrors/electron/v6.0.9/electron-v6.0.9-darwin-x64.zip) +0ms
  @electron/get:index Cache miss +1ms
  @electron/get:index Downloading http://npm.taobao.org/mirrors/electron/v6.0.9/electron-v6.0.9-darwin-x64.zip to /var/folders/r2/gy282f1163g_jd6pr1v_xmnh0000gn/T/electron-download-ef1mLy/electron-v6.0.9-darwin-x64.zip with options: undefined +40ms
Response code 404 (Not Found)

**Comment by wenbingzhang** [comment]
macos env add `export ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/`

**Comment by malept** [comment]
This is not a bug with Electron Packager, but rather the Taobao mirror is not up-to-date. Please file a bug with that service.

**Comment by jxf114208** [comment]
There is more v in the address.
**https://npm.taobao.org/mirrors/electron/v6.0.9/electron-v6.0.9-linux-x64.zip** This can't be downloaded

**https://npm.taobao.org/mirrors/electron/6.0.9/electron-v6.0.9-linux-x64.zip**This can be downloaded

**Comment by egoist** [comment]
The workaround is to use a fixed version:

```bash
npm config set electron_mirror "https://npm.taobao.org/mirrors/electron/"
npm config set electron_custom_dir "7.0.0"
```

**Comment by malept** [comment]
See: https://github.com/electron/get/issues/120
