### ISSUE TITLE
bindings.node is not a valid Win32 application

### ISSUE THREAD

**Issue by hannyudayana** [electron/electron-packager#1051]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 14.0.6
* **Electron Version:**
  * 6.0.9
* **Electron Rebuild:**
  * 1.8.6
* **Operating System:**
  * win32 10.0.17763 (x64)
* **Last Known Working Electron Packager version:**:
  * N/A

### Expected Behavior

Ran "npx electron-packager . --all --overwrite"
Generated for all platforms
All platforms running well

### Actual Behavior

Ran "npx electron-packager . --all --overwrite"
Generated for all platforms
Only Win32-ia32 is not running as per expected behavior
Error log:
`Error: \\?\D:\MyProject-win32-ia32\resources\app\node_modules\@serialport\bindings\build\Release\bindings.node is not a valid Win32 application.`
`\\?\D:\MyProject-win32-ia32\resources\app\node_modules\@serialport\bindings\build\Release\bindings.node`
`    at process.func (electron/js2c/asar.js:155)`
`    at process.func [as dlopen] (electron/js2c/asar.js:155)`
`    at Object.Module._extensions..node (internal/modules/cjs/loader.js:828)`
`    at Object.func (electron/js2c/asar.js:155)`
`    at Object.func [as .node] (electron/js2c/asar.js:155)`
`    at Module.load (internal/modules/cjs/loader.js:645)`
`    at Function.Module._load (internal/modules/cjs/loader.js:560)`
`    at Module.require (internal/modules/cjs/loader.js:685)`
`    at require (internal/modules/cjs/helpers.js:16)`
`    at bindings (D:\MyProject-win32-ia32\resources\app\node_modules\@serialport\bindings\node_modules\bindings\bindings.js:112)`

### To Reproduce

CLI: npx electron-packager . --all --overwrite

### Additional Information

I cloned the electron-quick-start guide from https://github.com/electron/electron-quick-start
Based on that code, I created a server app using express js https://www.npmjs.com/package/express
The server will be used to print to a thermal printer using escpos https://www.npmjs.com/package/escpos

**Comment by malept** [comment]
This is not a bug in Electron Packager. Native node modules will not work if you use `--all` for a couple of reasons:

1. You're not using the [electron-rebuild hook for Packager](https://github.com/electron/electron-rebuild#how-can-i-integrate-this-into-electron-packager)
2. Due to limitations with the Node.js ecosystem, it is not currently possible to cross-compile native modules (i.e., compile a native module on a Windows host for a macOS target).

You will need to use the rebuild hook, and then build the Electron app on each OS you intend on targeting.
