### ISSUE TITLE
Windows 10 Pro - Stuck up (ECONNRESET)

### ISSUE THREAD

**Issue by AaronTrazona** [electron/electron-packager#1062]
### Preflight Checklist

* [ ] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version: 14.0.6
  * 
* **Electron Version: 6.0.9
  * 
* **Operating System: Windows 10 PRO
  * 
* **Last Known Working Electron Packager version:**:
  * 

### Actual Behavior

I received read ECONNRESET
### Additional Information
Its possible that we have like a debug mode so that we can trace up the issue.
can you tell me where I can find the logs if there is?
![2019-10-24_0914](https://user-images.githubusercontent.com/1627816/67445457-92eeb200-f63f-11e9-921c-a2ebbc0e2234.png)

**Comment by malept** [comment]
> Its possible that we have like a debug mode so that we can trace up the issue.

See our [debugging documentation](https://github.com/electron/electron-packager/blob/v14.0.6/CONTRIBUTING.md#debugging).

`ECONNRESET` is a network problem. Your machine probably has trouble downloading Electron itself from GitHub releases.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community).

**Comment by AaronTrazona** [comment]
Yeah, I found out that issue. My concern right now, can we add some debug mode with doing a package? So that we can know what really happen in the background process. (if possible though)

**Comment by malept** [comment]
> can we add some debug mode

I linked to it in my previous comment.

**Comment by AaronTrazona** [comment]
Sorry, I missed that one. Thanks
