### ISSUE TITLE
Typescript package support

### ISSUE THREAD

**Issue by jo-wu** [electron/electron-packager#1063]
When I using electron-packager to package electron-quick-start-typescript,
it packaged successfully, but the out put app doesn't work well. 
I try to package js version of quick-start that works well.
What should I suppose to deal with it?

**Comment by malept** [comment]
You can use Electron Forge (v6), which has first-class support for Webpack. Adding TypeScript support to Electron Packager is outside of its scope, and can be added through the use of hooks (e.g., running `tsc` in an [`afterCopy` hook](https://github.com/electron/electron-packager/blob/v14.0.6/docs/api.md#aftercopy)).

If you need more assistance, please use one of the [community forums](https://electronjs.org/community).
