### ISSUE TITLE
maintain different paths for asar packing

### ISSUE THREAD

**Issue by wgrhstf** [electron/electron-packager#1066]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
For fast changes in my CSS files and replacing images when packed I have to store some CSS and image files in separate folders outside the asar. So I have to rewrite all the path to those files inside my HTML & CSS files for packaging. Otherwise they won't work in development.

### Proposed Solution
A system where it is possible to maintain alternative paths in CSS and HTML files that get activated/deactivated when packing asar.
E.g.:
```
<!--packager-forasar
<link rel="stylesheet" href="../myexternalFolder/user.css">
-->
<!--for-development-start-->
<link rel="stylesheet" href="user.css">
<!--for-development-end-->
```
or
```
/* packager-forasar
background-image: url("../myexternalFolder/logo.png");
*/
/* for-development-start/*
background-image: url("grfx/logo.png");
/* for-development-end/*
```

**Comment by malept** [comment]
The proposed solution doesn't make sense to live in Electron Packager proper, as the development and maintenance effort far exceeds the amount of users affected. It would make more sense to have this as a plugin to Electron Packager, using a hook such as [`afterCopy`](https://github.com/electron/electron-packager/blob/v14.1.0/docs/api.md#aftercopy). If you do decide to make the plugin and open source it, I would be happy to link to it in the [plugins section of the README](https://github.com/electron/electron-packager/blob/v14.1.0/README.md#plugins).
