### ISSUE TITLE
Inferring doesn't give very good errors when it can't find a package.json

### ISSUE THREAD

**Issue by Qws** [electron/electron-packager#1072]
### Issue Details

Using this in Windows's CLI gives me an error:
`electron-packager .. barcode --platform=win32 --arch=ia32`

But this works fine:
`electron-packager . barcode --platform=win32 --arch=ia32`

So apparently single `.` works, but twice `..` doesn't?

I want to compile electron app one directory above the project directory. Using `.` selects the current project directory, so `..` should get me to one directory above. Sadly it doesn't work, but it's not really a problem, it's not my main issue at all, it's just that the error is (imo) unclear and not detailed.

The error:
`Unable to determine [Unknown Property]. Please specify an [Unknown Property]`

My main problem is that it doesn't notify where the exact issue was. I just had to guess that I can't use `..` as a CLI argument on Windows (so far I know).

The barcode Electron project is located in `C:\\Users\myWinUsername\Documents\Projects\Nodejs\barcode\`

* **Electron Packager Version:**
  * 14.1.0
* **Electron Version:**
  * 7.0.1
* **Operating System:**
  * Windows 10 (Microsoft Windows [Version 10.0.18362.418])

### Expected Behavior

`electron-packager .. barcode --platform=win32 --arch=ia32`

I expected using `..` as path argument to go one directory up, or at least tell me I can't use the `..`

### Actual Behavior

It gave me an: 
`Unable to determine [Unknown Property]. Please specify an [Unknown Property]`

### To Reproduce
I think this problem occurs for any Electron app compilation on Windows where you give `..` as an argument for `electron-packager` CLI command.

So on a simple Electron project, give `..` as the compiled result directory path.

I won't be surprised if this problem doesn't occur on Linux or Mac, but I haven't tested it.

### Additional Information
<!--

**Comment by malept** [comment]
I can't reproduce this on Linux. Here are the steps I used:

```shell
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm install --save-dev electron-packager
mkdir subdir
cd subdir
../node_modules/.bin/electron-packager ..
```
In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

**Comment by Qws** [comment]
@malept 
So you were able to compile/export electron project with `..` as bin destination?

I tried it on another Windows PC and I got the same error, `..` , exporting outside project directory is not a valid option?

Well, here is the log I get with `DEBUG=electron-packager`:

```
C:\Users\deno\Documents\Projects\Nodejs\label-printer>electron-packager .. barcode --platform=win32 --arch=ia32
  electron-packager Electron Packager 14.1.0
  electron-packager Node v12.13.0
  electron-packager Host Operating system: win32 10.0.18362 (x64) +0ms
  electron-packager Packager Options: {"_":["..","barcode"],"platform":"win32","arch":"ia32","deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"dir":"..","name":"barcode","protocols":[]} +3ms
  electron-packager Target Platforms: win32 +1ms
  electron-packager Target Architectures: ia32 +1ms
  electron-packager Unable to find all properties in parent package.json files. Missing props: "version", ["dependencies.electron","devDependencies.electron","dependencies.electron-nightly","devDependencies.electron-nightly","dependencies.electron-prebuilt-compile","devDependencies.electron-prebuilt-compile","dependencies.electron-prebuilt","devDependencies.electron-prebuilt"], "author" +0ms
Unable to determine [Unknown Property]. Please specify an [Unknown Property]

For more information, please see
https://github.com/electron/electron-packager/blob/master/docs/api.md#

Unable to determine Electron version. Please specify an Electron version

For more information, please see
https://github.com/electron/electron-packager/blob/master/docs/api.md#electronversion

Unable to determine [Unknown Property]. Please specify an [Unknown Property]

For more information, please see
https://github.com/electron/electron-packager/blob/master/docs/api.md#



C:\Users\deno\Documents\Projects\Nodejs\label-printer>
```

Using `..` as argument sadly doesn't work on Windows. Here log with `.` as argument this works fine:

```
C:\Users\deno\Documents\Projects\Nodejs\label-printer>electron-packager . barcode --platform=win32 --arch=ia32
  electron-packager Electron Packager 14.1.0
  electron-packager Node v12.13.0
  electron-packager Host Operating system: win32 10.0.18362 (x64) +0ms
  electron-packager Packager Options: {"_":[".","barcode"],"platform":"win32","arch":"ia32","deref-symlinks":true,"derefSymlinks":true,"download":{"rejectUnauthorized":true,"reject-unauthorized":true},"junk":true,"prune":true,"dir":".","name":"barcode","protocols":[]} +2ms
  electron-packager Target Platforms: win32 +0ms
  electron-packager Target Architectures: ia32 +1ms
  electron-packager Inferring appVersion from version in C:\Users\deno\Documents\Projects\Nodejs\label-printer\package.json +0ms
  electron-packager Inferring win32metadata.CompanyName from author in C:\Users\deno\Documents\Projects\Nodejs\label-printer\package.json +1ms
  electron-packager Inferring target Electron version from electron in C:\Users\deno\Documents\Projects\Nodejs\label-printer\package.json +6ms
  electron-packager Application name: barcode +16ms
  electron-packager Target Electron version: 7.0.1 +1ms
  electron-packager Ignored path regular expressions: [ '/\\.git($|/)', '/node_modules/\\.bin($|/)', '\\.o(bj)?$' ] +0ms
  electron-packager Downloading Electron with options {"rejectUnauthorized":true,"reject-unauthorized":true,"platform":"win32","arch":"ia32","version":"7.0.1","artifactName":"electron"} +0ms
Packaging app for platform win32 ia32 using electron v7.0.1
  electron-packager Creating C:\Users\deno\AppData\Local\Temp\electron-packager\win32-ia32-template +9ms
  electron-packager Extracting C:\Users\deno\AppData\Local\electron\Cache\httpsgithub.comelectronelectronreleasesdownloadv7.0.1electron-v7.0.1-win32-ia32.zip\electron-v7.0.1-win32-ia32.zip to C:\Users\deno\AppData\Local\Temp\electron-packager\win32-ia32-template +3ms
  electron-packager Initializing app in C:\Users\deno\AppData\Local\Temp\electron-packager\win32-ia32\barcode-win32-ia32 from C:\Users\deno\AppData\Local\Temp\electron-packager\win32-ia32-template template +0ms
  electron-packager Ignored paths based on the out param: [
  'C:\\Users\\deno\\Documents\\Projects\\Nodejs\\label-printer\\barcode-darwin-x64',
  'C:\\Users\\deno\\Documents\\Projects\\Nodejs\\label-printer\\barcode-linux-ia32',
  'C:\\Users\\deno\\Documents\\Projects\\Nodejs\\label-printer\\barcode-linux-x64',
  'C:\\Users\\deno\\Documents\\Projects\\Nodejs\\label-printer\\barcode-linux-armv7l',
  'C:\\Users\\deno\\Documents\\Projects\\Nodejs\\label-printer\\barcode-linux-arm64',
  'C:\\Users\\deno\\Documents\\Projects\\Nodejs\\label-printer\\barcode-linux-mips64el',
  'C:\\Users\\deno\\Documents\\Projects\\Nodejs\\label-printer\\barcode-mas-x64',
  'C:\\Users\\deno\\Documents\\Projects\\Nodejs\\label-printer\\barcode-win32-ia32',
  'C:\\Users\\deno\\Documents\\Projects\\Nodejs\\label-printer\\barcode-win32-x64',
  'C:\\Users\\deno\\Documents\\Projects\\Nodejs\\label-printer\\barcode-win32-arm64'
] +6s
  electron-packager Renaming electron.exe to barcode.exe in C:\Users\deno\AppData\Local\Temp\electron-packager\win32-ia32\barcode-win32-ia32 +6s
  electron-packager Running rcedit with the options {"version-string":{"FileDescription":"barcode","InternalName":"barcode","OriginalFilename":"barcode.exe","ProductName":"barcode","CompanyName":"deno suresan"},"file-version":"1.0.0","product-version":"1.0.0"} +0ms
  electron-packager Moving C:\Users\deno\AppData\Local\Temp\electron-packager\win32-ia32\barcode-win32-ia32 to C:\Users\deno\Documents\Projects\Nodejs\label-printer\barcode-win32-ia32 +2s
Wrote new app to C:\Users\deno\Documents\Projects\Nodejs\label-printer\barcode-win32-ia32

C:\Users\deno\Documents\Projects\Nodejs\label-printer>
```

**Comment by malept** [comment]
I'm confused, does `C:\Users\deno\Documents\Projects\Nodejs` contain an Electron app? (Meaning, does `C:\Users\deno\Documents\Projects\Nodejs` have a `package.json` file with `electron` in its devDependencies`?)

**Comment by Qws** [comment]
`C:\Users\deno\Documents\Projects\Nodejs` does not contain an Electron app/package.json, it's a regular directory.

`C:\Users\deno\Documents\Projects\Nodejs\label-printer` this is the source-code project, but I wanted to compile and export files 1 directory above the source-code directory, so in the regular `C:\Users\deno\Documents\Projects\Nodejs` is where I wanted the packaged electron app to be exported.

I guess I misunderstood the `electron-packager parameters`. But my real problem was that the error message gave me no hints why the compiling failed.
