### ISSUE TITLE
Add support for minify

### ISSUE THREAD

**Issue by yafp** [electron/electron-packager#1081]
### Preflight Checklist
* [ x ] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
If i understand it right, electron-packager does not minify the js /css code while packaging

### Proposed Solution
It would be perfect if electron-packager would minify the css / js code while packaging

### Additional Information
If i am overlooking a known & good alternatives i would be happy about a keyword / hint

**Comment by malept** [comment]
This is outside the scope of Electron Packager. What you should do is run your minifier before you run Electron Packager, and then set the `ignore` option to ignore the non-minified code. This is what Electron Forge v6 does with its Webpack support.
