### ISSUE TITLE
--osx-sign supplied twice in the command line

### ISSUE THREAD

**Issue by pieterdt** [electron/electron-packager#1086]
### Preflight Checklist

* [x ] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  *  14.0.6
* **Electron Version:**
  * 6.0.12 -->
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
When running electron-packager with the documented osx-sign options on the command line I expect osx-sign to be using them

### Actual Behavior
It seems in my case at least that the structure of the options that is passed to osx-sign is not in a way that osx-sign can properly work. As a consequence, it tries to get by and resolves e.g. the identity on it's own. My problem sits in the fact that the osx-sign.entitlements option is not passed to osx-sign.
Where I was thinking that the osx-sign options would be an object of the form like
`{
   identity: XYZ,
  entitlements: pathX
}`

What I see when debugging is a structure of the form
`{
   0: {identity: XYZ}, 1: {entitlements: pathX}, ....
}`

This explains why osx-sign when running in debug mode reports something along the following lines:
`> Application: /var/folders/f7/2tqdw_2j353cf2_700_lmnnm0000gn/T/electron-packager/darwin-x64/MyAPP-darwin-x64/MyAPP.app
 > Platform: darwin
 > Entitlements: undefined
 > Child entitlements: undefined
 > Additional binaries: undefined
 > Identity: {
  name: 'Developer ID Application: MYID',
  hash: 'SOMEHASH'
}`
### To Reproduce
Can't share a repo for now, sorry.

### Additional Information
osx-sign version is 0.14.4
I find this weird, as if this was the normal behaviour that everyone would see, there would probably be more reports of the problem...

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What command line arguments are you passing?

**Comment by pieterdt** [comment]
ok to run it without osx-sign in debug mode?

**Comment by malept** [comment]
You don't have to put in secret values. If the bug exists, it won't matter if the values are wrong. Please run `electron-packager` with debug enabled.

**Comment by pieterdt** [comment]
command line:
`electron-packager ./ MyAppName --platform=darwin --arch=x64 --out ./dist/ --overwrite --icon=src/logo.icns --osx-sign  --appCopyright='2019 XXX'  --osx-sign.identity='Developer ID Application: MYDEVID' --osx-sign.entitlements=./entitlements.mac.plist --osx-sign.entitlements-inherit=entitlements.mac.plist --appBundleId='MYBUNDLEID'  --app-category-type='public.app-category.music'`

Interesting bit in the output (running in debug):
`electron-packager Running electron-osx-sign with the options {"0":true,"1":{"identity":"Developer ID Application: MYDEVID"},"2":{"identity":"Developer ID Application: MYDEVID"},"3":{"entitlements":"./entitlements.mac.plist"},"4":{"entitlements":"./entitlements.mac.plist"},"5":{"entitlementsInherit":"entitlements.mac.plist"},"6":{"entitlements-inherit":"entitlements.mac.plist"},"platform":"darwin","app":"/var/folders/f7/2tqdw_2j353cf2_700_lmnnm0000gn/T/electron-packager/darwin-x64/MyApp-darwin-x64/MyApp.app","version":"6.0.12","hardenedRuntime":true}`

still need the full log?

**Comment by malept** [comment]
You have set `--osx-sign` in addition to `--osx-sign.entitlements`. Get rid of the `--osx-sign` before `--appCopyright` and it will work.

**Comment by pieterdt** [comment]
well, I'll be damned... this fixed it! I tried this before in an earlier attempt, but got the message then that signing was not requested. Must have made another error then...

Thanks for your super fast support!
