### ISSUE TITLE
packing for Mac gives a path error, and fails

### ISSUE THREAD

**Issue by wgrhstf** [electron/electron-packager#1100]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  6.13.4
* **Electron Version:**
  7.1.8
* **Operating System:**
  Windows 10 1909 / MacOS 10.11.6
* **Last Known Working Electron Packager version:**:
  * 

### Expected Behavior
Tried to Pack my App for MacOS on Windows 10 and MacOS for MacOS

### Actual Behavior
electron-packager stopped with an error Message
"the path argument must be one of type string buffer or url. received type undefined"

### To Reproduce
In my package.json I run the script
`"pack-mac": "electron-packager . Presentations --overwrite --asar --platform=darwin --arch=x64 --prune=true --out=dist --icon=./pathTo/my.ico --ignore=^/files --ignore=^/.idea --ignore=^/.git"`

### Additional Information
The same line works fine for --platform=win32, Tried to buildt on Windows and Mac with the same error.
This is the log if it may be of any help:

> 0 info it worked if it ends with ok
> 1 verbose cli [
> 1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
> 1 verbose cli   'C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
> 1 verbose cli   'run',
> 1 verbose cli   'pack-mac'
> 1 verbose cli ]
> 2 info using npm@6.13.4
> 3 info using node@v12.13.0
> 4 verbose run-script [ 'prepack-mac', 'pack-mac', 'postpack-mac' ]
> 5 info lifecycle RoomClient@0.1.0\~prepack-mac: RoomClient@0.1.0
> 6 info lifecycle RoomClient@0.1.0\~pack-mac: RoomClient@0.1.0
> 7 verbose lifecycle RoomClient@0.1.0\~pack-mac: unsafe-perm in lifecycle true
> 8 verbose lifecycle RoomClient@0.1.0\~pack-mac: PATH: C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;D:\myApp\Software\SC\Client\node_modules\.bin;D:\ImageMagick-7.0.5-Q16;C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\GtkSharp\2.12\bin;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files (x86)\Gpg4win\..\GnuPG\bin;C:\Users\me\AppData\Local\.meteor\;C:\Users\me\AppData\Local\Microsoft\WindowsApps;C:\Users\me\AppData\Roaming\npm
> 9 verbose lifecycle RoomClient@0.1.0\~pack-mac: CWD: D:\myApp\Software\SC\Client
> 10 silly lifecycle RoomClient@0.1.0\~pack-mac: Args: [
> 10 silly lifecycle   '/d /s /c',
> 10 silly lifecycle   'electron-packager . Presentations --overwrite --platform=darwin --arch=x64 --prune=true --out=dist --icon=./pathTo/my.ico '
> 10 silly lifecycle ]
> 11 silly lifecycle RoomClient@0.1.0\~pack-mac: Returned: code: 1  signal: null
> 12 info lifecycle RoomClient@0.1.0\~pack-mac: Failed to exec pack-mac script
> 13 verbose stack Error: RoomClient@0.1.0 pack-mac: `electron-packager . Presentations --overwrite --platform=darwin --arch=x64 --prune=true --out=dist --icon=./pathTo/my.ico `
> 13 verbose stack Exit status 1
> 13 verbose stack     at EventEmitter.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
> 13 verbose stack     at EventEmitter.emit (events.js:210:5)
> 13 verbose stack     at ChildProcess.<anonymous> (C:\Users\me\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
> 13 verbose stack     at ChildProcess.emit (events.js:210:5)
> 13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
> 13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
> 14 verbose pkgid RoomClient@0.1.0
> 15 verbose cwd D:\myApp\Software\SC\Client
> 16 verbose Windows_NT 10.0.18363
> 17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\me\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "pack-mac"
> 18 verbose node v12.13.0
> 19 verbose npm  v6.13.4
> 20 error code ELIFECYCLE
> 21 error errno 1
> 22 error RoomClient@0.1.0 pack-mac: `electron-packager . Presentations --overwrite --platform=darwin --arch=x64 --prune=true --out=dist --icon=./pathTo/my.ico `
> 22 error Exit status 1
> 23 error Failed at the RoomClient@0.1.0 pack-mac script.
> 23 error This is probably not a problem with npm. There is likely additional logging output above.
> 24 verbose exit [ 1, true ]
>

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.

**Comment by wgrhstf** [comment]
Sorry - I just fond out.
If `--icon=./pathTo/my.ico` is replaced with `--icon=./pathTo/my.icns` the build works.

So it's just the error message which is a bit misleading.
