### ISSUE TITLE
Mac App Store only accepts .pkg files

### ISSUE THREAD

**Issue by rlingineni** [electron/electron-packager#1106]
### Preflight Checklist

* [X] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [X] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
*Latest*
* **Electron Version:**
*Latest*
* **Operating System:**
*MacOS Mojave*
* **Last Known Working Electron Packager version:**:

### Expected Behavior
I'm trying to figure out how to package my app for the App Store. 

It seems that for the App Store - the accepted binary type is a `.pkg`. However, electron packager is outputting a `.app`.

There are a few options that the Mac OS App store seems to provide tools such as [transporter and altTool](https://help.apple.com/app-store-connect/#/devb1c185036) to upload my binaries but they all seem to only accept extensions of the type `.pkg`. 

### Actual Behavior
When I run `electron-packager` my output is of type `.app`

I am unsure if there is something else I am missing to publish to the store. Or if `.app` can be submitted to the store.

### Repro

`electron-packager . --out ./dist --overwrite --icon=electron/icons/AppIcon.icns --platform mas`

I then sign it with `electron-osx-sign` and put the provisioning profile in the same directory as the `.app`

**Comment by malept** [comment]
[Electron Forge](https://www.electronforge.io/) (which uses Electron Packager internally) has first-class support for `.pkg` files: https://www.electronforge.io/config/makers/pkg

Electron Packager is meant to customize and bundle Electron apps. Making distributables is meant for either [separate modules](https://github.com/electron/electron-packager/blob/v14.2.0/README.md#distributable-creators) or Electron Forge.
