### ISSUE TITLE
Change only necessary files.

### ISSUE THREAD

**Issue by hickorysb** [electron/electron-packager#1108]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

I am bundling this with a Unity game, I don't want to hear anybody's opinions on how bad this idea might be, but every time I compile the client I have to reimport all of it into Unity because repackaging deletes and recreates everything.
### Proposed Solution

I would prefer that it only replaces/removes/adds files that have changed in their respective manner.
### Alternatives Considered

I would accept any solution that would make it not have to be imported into Unity every-time that I rebuild it.
### Additional Information

This would also be useful for people who might want to use a Git repo to host updates for their applications. As it is GitHub will see each build as a deletion and creation of a whole new set of files. Causing the build machine to reupload everything, and the client to redownload everything. Which is not very bandwidth efficient.

**Comment by malept** [comment]
I think this feature would end up being too complex for the number of users that need it. You can make this feature yourself without changing the Electron Packager code, with something like this pseudocode:

```javascript
const fs = require('fs-extra')
const packager = require('electron-packager')
const path = require('path')

async function generateChecksum(filename) {
  // generates SHA256 checksum of the contents of filename, an exercise for the reader
}

function generateFilterFunction(fromDir, toDir) {
  return async function (filename) {
    const relative = path.relative(fromDir, filename)
    if (!(await fs.pathExists(path.join(toDir, relative)))) {
      return true
    }

    if ((await generateChecksum(path.join(fromDir, relative)) !== (await generateChecksum(toDir, relative))) {
      return true
    }

    return false
  }
}

async function packageAndCopyNewOrUpdatedFiles(realOutDir) {
  const tmpDir = await fs.mkdtemp()
  const packagedDirs = await packager({
    out: tmpDir,
    // ... your other options
  })
  await fs.copy(packagedDirs[0], realOutDir, { filter: generateFilterFunction(packagedDirs[0], realOutDir) })
  await fs.remove(tmpDir)
}
```

> This would also be useful for people who might want to use a Git repo to host updates for their applications. As it is GitHub will see each build as a deletion and creation of a whole new set of files. Causing the build machine to reupload everything, and the client to redownload everything. Which is not very bandwidth efficient.

This is not a good idea, as Git is not a good way to keep track of binary file changes. Using GitHub Releases in conjunction with [`update-electron-app`](https://github.com/electron/update-electron-app) is the recommended way to do this.
