### ISSUE TITLE
Statically compile electron app athenapdf with electron-packager?

### ISSUE THREAD

**Issue by sxiii** [electron/electron-packager#1113]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I have a specific version of linux distro with specific libraries set etc. I would like to build "[athenapdf](https://github.com/arachnys/athenapdf/)" project for my specific platform. It uses electron-packager. I've tried to find information on how to build electron statically but I wasn't able to do it actually.

### Proposed Solution
Provide a static build options for packaged applications

### Alternatives Considered
Either electron or chromium has to be statically build; but I was unable to do it.

### Additional Information
Is it achievable at all?

**Comment by malept** [comment]
Electron Packager does not compile the source code of Electron. Rather, it utilizes the prebuilt Electron binaries to customize and bundle Electron apps.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community).
