### ISSUE TITLE
Trying to --unpack and it's not working 

### ISSUE THREAD

**Issue by BrsDreamer** [electron/electron-packager#1124]
hello there sorry for the sudden issue but was wondering i you could help me around a bit? 
im using node-notifier so as peer of using electron-packager after packing node-notifier the icons for the node are not showing and after searching around and came to the solution that the node-notifier documents said about using --unpack "./node_modules/node-notifier/vendor/**" so i tryed using this on my electron-packager script and im not getting any output from it and the issue still presist

this is my electron-packager script:  electron-packager . ParsWebScrapper --overwrite --asar=true ----unpack-asar-dir=./node_modules/node-notifier/vendor/** --platform=win32 --arch=ia32 --icon=img/app.ico --prune=true --out=release-builds --version-string.CompanyName=CE --version-string.FileDescription=CE --version-string.ProductName=ParsWebScrapper

note: i readed another issue about this and it seems one of u guys said something about --unpack-asar-dir on electron-packager being available but still after using it issue still presist
would really appreciate it if u could give me hand thanks ...

**Comment by malept** [comment]
Look at `electron-packager --help` and the API docs. I've linked to the docs for 14.2.1 below:

https://github.com/electron/electron-packager/blob/9829f9946b8b25abf2b7fa129c22cf5fdb25de44/usage.txt#L27-L37

https://github.com/electron/electron-packager/blob/v14.2.1/docs/api.md#asar

If you need more assistance, please use one of the [community forums](https://electronjs.org/community).
