### ISSUE TITLE
Cannot find wine64 despite wine-stable installed via homebrew

### ISSUE THREAD

**Issue by LittleHamster** [electron/electron-packager#1129]
I am using mac and I cloned the `electron-quick-start` repo. 
If I do `electron-packager . --all` I get this error:

```
Could not find "wine64" on your system.

Wine is required to use the appCopyright, appVersion, buildVersion, icon, and 
win32metadata parameters for Windows targets.

Make sure that the "wine64" executable is in your PATH.
```

I am not sure what this means, I installed Wine using: https://wiki.winehq.org/MacOS
`brew cask install wine-stable`

All I want is to be able to generate a portable exe file to open the app on Windows machines

**Comment by malept** [comment]
What version of macOS do you have installed?

**Comment by LittleHamster** [comment]
Mac 10.14.6

**Comment by malept** [comment]
What do you get when you run the following commands:

```
which wine
which wine64
which wineserver
ls "/Applications/Wine Stable.app/Contents/Resources/wine/bin"

**Comment by LittleHamster** [comment]
I fixed the issue by installed wine-devel
`brew install homebrew/cask-versions/wine-devel`

**Comment by lucashoeft** [comment]
I ran into the same problem, but I had wine-stable installed which unfortunalty didn't work. I fixed it by deinstalling wine-stable and installing wine-devel.

**Comment by zongzi531** [comment]
> I fixed the issue by installed wine-devel `brew install homebrew/cask-versions/wine-devel`

Thanks, It is work for me.

**Comment by parin13** [comment]
im getting error trying to install using command : 
`brew install homebrew/cask-versions/wine-devel`

error looks like: 
`Error: homebrew/cask-versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.`

**Comment by akcware** [comment]
> im getting error trying to install using command : `brew install homebrew/cask-versions/wine-devel`
> 
> error looks like: `Error: homebrew/cask-versions was deprecated. This tap is now empty and all its contents were either deleted or migrated.`

`sudo ln -s "$(which wine)" /usr/local/bin/wine64`
works for me.
