### ISSUE TITLE
Set minimum macOS system with LSMinimumSystemVersion

### ISSUE THREAD

**Issue by debelop13** [electron/electron-packager#1138]
* [ x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
I want to block application launch, for example, in Yosemite 10.10

### Proposed Solution
An option to set LSMinimumSystemVersion from Info.plist

**Comment by malept** [comment]
Is there a reason why using [`extendInfo`](https://github.com/electron/electron-packager/blob/v14.2.1/docs/api.md#extendinfo) doesn't work for you?

**Comment by debelop13** [comment]
Sorry, i didn't see this option

It works perfect
