### ISSUE TITLE
I bumped with electron-pacakger dependency vulnerability

### ISSUE THREAD

**Issue by serhiyzablotskiy** [electron/electron-packager#1141]
<img width="583" alt="Screen Shot 2020-04-02 at 11 46 51 AM" src="https://user-images.githubusercontent.com/7163430/78229336-874dc400-74d8-11ea-9cce-94e13b4e76dc.png">

**Comment by malept** [comment]
The first two are specific to your app. The Electron one and the Electron Packager one aren't actually used because neither use mkdirp via its CLI.
