### ISSUE TITLE
Un able to package electron app. ENOENT: no such file or directory,

### ISSUE THREAD

**Issue by mehdisaqlen** [electron/electron-packager#1143]
I have tried more than 20 times to package the application built with an electron but failed. I do not want the issue is. I have seen many tutorials on YouTube and on the internet even then I could not package the app. When I run the command electron-packager .  Please help me ho do I solve this issue?
here is my packaje.json file:

`{
  "name": "myapp",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "dependencies": {
    "electron": "^8.2.3"
  },
  "devDependencies": {
    "electron-packager": "^14.2.1"
  },
  "scripts": {
    "start": "electron ."
  },
  "author": "",
  "license": "ISC"
}

here is a screenshot of an issue:
<img width="946" alt="Untitled" src="https://user-images.githubusercontent.com/52012642/79866973-72a37400-8392-11ea-88d2-620f15b4f28d.png">

**Comment by sherebiahtishbi** [comment]
I have same issue.  All the details are mentioned below

**on the powershell it says** 
Packaging app for platform win32 x64 using electron v8.2.3
ENOENT: no such file or directory, rename 'C:\Users\SHEREB~1\AppData\Local\Temp\electron-packager\win32-x64\sermon-downloader-2.0-win32-x64\electron.exe' -> 'C:\Users\SHEREB~1\AppData\Local\Temp\electron-packager\win32-x64\sermon-downloader-2.0-win32-x64\sermon-downloader-2.0.exe'

**Below is the log from the logs file**
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'package-win'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.16.3
4 verbose run-script [ 'prepackage-win', 'package-win', 'postpackage-win' ]
5 info lifecycle sermon-downloader-2.0@2.0.0~prepackage-win: sermon-downloader-2.0@2.0.0
6 info lifecycle sermon-downloader-2.0@2.0.0~package-win: sermon-downloader-2.0@2.0.0
7 verbose lifecycle sermon-downloader-2.0@2.0.0~package-win: unsafe-perm in lifecycle true
8 verbose lifecycle sermon-downloader-2.0@2.0.0~package-win: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\SermonindexPlayer2.0\node_modules\.bin;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\Sherebyah Tisbi\AppData\Local\Microsoft\WindowsApps;;C:\Users\Sherebyah Tisbi\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\Sherebyah Tisbi\AppData\Roaming\npm
9 verbose lifecycle sermon-downloader-2.0@2.0.0~package-win: CWD: C:\SermonindexPlayer2.0
10 silly lifecycle sermon-downloader-2.0@2.0.0~package-win: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   "electron-packager ./ sermon-downloader-2.0 --overwrite --asar --icon=images/sermonindex_logo.ico --out=release-builds --win32metadata.CompanyName='Sermonindex.com' --win32metadata.FileDescription='sermon-downloader-2.0' --win32metadata.ProductName='Sermon Downloader 2.0'"
10 silly lifecycle ]
11 silly lifecycle sermon-downloader-2.0@2.0.0~package-win: Returned: code: 1  signal: null
12 info lifecycle sermon-downloader-2.0@2.0.0~package-win: Failed to exec package-win script
13 verbose stack Error: sermon-downloader-2.0@2.0.0 package-win: `electron-packager ./ sermon-downloader-2.0 --overwrite --asar --icon=images/sermonindex_logo.ico --out=release-builds --win32metadata.CompanyName='Sermonindex.com' --win32metadata.FileDescription='sermon-downloader-2.0' --win32metadata.ProductName='Sermon Downloader 2.0'`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:310:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:310:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid sermon-downloader-2.0@2.0.0
15 verbose cwd C:\SermonindexPlayer2.0
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "package-win"
18 verbose node v12.16.3
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error sermon-downloader-2.0@2.0.0 package-win: `electron-packager ./ sermon-downloader-2.0 --overwrite --asar --icon=images/sermonindex_logo.ico --out=release-builds --win32metadata.CompanyName='Sermonindex.com' --win32metadata.FileDescription='sermon-downloader-2.0' --win32metadata.ProductName='Sermon Downloader 2.0'`
22 error Exit status 1
23 error Failed at the sermon-downloader-2.0@2.0.0 package-win script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by malept** [comment]
I can't reproduce this on Windows 10 Home. Steps I used to test this:

```
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm install --save-dev electron-packager
.\node_modules\.bin\electron-packager .
```

In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base (as shown above), could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by sherebiahtishbi** [comment]
Thanks for your comment. After bit more research I found few more things

1. My icon file was missing, I added that file. Surprisingly error log doesn't say anything about the missing file. The way I found it is executing script at the terminal $>electron-packager and not as npm run.

2. After adding icon file the script works fine from terminal as standalone script but still getting the same error if ran as $>npm run <script>

Hope this helps and gives some pointers to reproduce.

**Comment by malept** [comment]
> the script works fine from terminal as standalone script but still getting the same error if ran as $>npm run <script>

I still can't reproduce this if I create the NPM script `"package": "electron-packager ."`.

> Surprisingly error log doesn't say anything about the missing file

This is unrelated to this particular issue but I get a warning about a missing icon file. Output:

```
PS C:\[...]\eqs> npm run package

> electron-quick-start@1.0.0 package C:\[...]\eqs
> electron-packager . --icon=nonexistent.ico

Packaging app for platform win32 x64 using electron v8.2.5
WARNING: Could not find icon "nonexistent.ico", not updating app icon
Wrote new app to C:\[...]\eqs\electron-quick-start-win32-x64
```

**Comment by hugoruscitti** [comment]
I had the same error message today, so i made this repo to try to reproduce the issue https://github.com/hugoruscitti/electron-packager-issue-1143

When i clone the repo and run the command "npm install" and then "npm run package" i get this error message:

![192 168 0 77 2020-05-12 23-27-02](https://user-images.githubusercontent.com/99183/81764975-1cb18000-94a9-11ea-8031-5af8c8fe27cb.png)

Then, i try different (random/crazy) things and i notice that the problems seems to be related to my "package-lock.json" file, that i made some time ago in osx.

This screenshot shows how things stats to work again if i remove the "node_package" folder and the "package-lock.json":

![image](https://user-images.githubusercontent.com/99183/81765320-df99bd80-94a9-11ea-931c-c78480ec429c.png)
