### ISSUE TITLE
Electron is too slow to download

### ISSUE THREAD

**Issue by TLHorse** [electron/electron-packager#1148]
`electron-packager` must download `electron` framework form GitHub every time when I'm packaging an app.

BUT THE PROBLEM IS, it is so slow to connect the GitHub CDN (`githubusercontent`) in China, which is not convenient.
It looks like this:
```
Downloading electron-v8.2.5-darwin-x64.zip: [============----------------------------------------------------------------------------------------] 12% ETA: 7258.9 seconds
```

The only way to connect `githubusercontent` in China is to change the `electron` repo url to a GitHub mirror URL. So how can I change it? Or, can I use a local folder as the `electron` framework repo.?

**Comment by malept** [comment]
This isn't a problem with Electron Packager itself. The [Electron documentation](https://www.electronjs.org/docs/tutorial/installation#mirror) indicates how to change the download location for folks in China.

**Comment by TLHorse** [comment]
I'm NOT DOWNLOADING ELEECTRON FROM NPM!

I mean: because I add `electron` in the `package.json` dependencies, so `electron-packager` is **default** downloading the `electron` package from GitHub (not from other mirrors), **every time** when I'm packing an app, and you **cannot** change it's mirror or download link.

**Comment by malept** [comment]
Both Electron Packager and the `electron` npm package use the same mechanism for downloading the prebuilt binaries (by design), so the environment variables will work the same.

**Comment by TLHorse** [comment]
> Both Electron Packager and the `electron` npm package use the same mechanism for downloading the prebuilt binaries (by design), so the environment variables will work the same.

Do you mean that `electron-packager` is using npm commands to download the `dependencies` and `devDependencies` in `package.json`?

**Comment by malept** [comment]
No, they both use the `@electron/get` node module to download the Electron prebuilt binaries, which is where the environment variables come into play.
