### ISSUE TITLE
🐛 Specifying a relative `icon` path for a new BrowserWindow breaks Windows build with Electron 9.0.0

### ISSUE THREAD

**Issue by ChrisAntaki** [electron/electron-packager#1150]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 14.2.1
* **Electron Version:**
  * 12.16.1
* **Operating System:**
  * win32 10.0.18363 (x64)
* **Last Known Working Electron Packager version:**:
  * 14.2.1 (with Electron 8.3.0)

### Expected Behavior
Packaged app should still be able to open browser windows with a relative `icon` path specified.

### Actual Behavior
Packaged app can't open `BrowserWindows` with a relative path `icon` field specified. Instead of rendering the page, nothing is written to the DOM. This started today when I upgraded Electron to `9.0.0`.

Workarounds:
- Specify an absolute `icon` path (ex: `__dirname + '/icon.png'`)
- Remove the `icon` field

### To Reproduce
- Clone this reprository https://github.com/ChrisAntaki/electron-packager-bug-repro
- Install dependencies with `yarn`
- Test the app locally with `yarn start`, it should work fine
- Package the app with `yarn package`, the packaged app should just show a white screen

**Comment by malept** [comment]
It's not recommended to use relative paths in Electron apps, see the [FAQ entry](https://github.com/electron/electron-packager/blob/v14.2.1/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working) for more details.

That being said, this sounds like a regression in Electron itself, not Electron. Electron Packager has no control over the `icon` option of the `BrowserWindow` constructor.
