### ISSUE TITLE
API documentation missing

### ISSUE THREAD

**Issue by LoLei** [electron/electron-packager#1154]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details
* Version: https://github.com/electron/electron-packager/commit/4d22659feaa929c8eb95fc7005ad05acd5d37a74

### Expected Behavior
Clicking on "API" at the top of the Readme should bring me to the API documentation.

### Actual Behavior
Clicking on "API" at the top of the Readme brings me to [this](https://electron.github.io/electron-packager/master/).  
Which is the same as the Readme. Clicking on "API" there brings me to the same page.

### Additional Information
https://github.com/electron/electron-packager/blob/master/docs/api.md says the API documentation has moved. Clicking on this  link there also redirects me to the page mentioned above.

I could also find nothing in the ["Community"](https://www.electronjs.org/community) section of Electron. Particularly frustrating that when trying to open an issue about this in this repo, it asks me to go there to ask questions about usage, only that that site is a general Electron site. Clicking on electron-packager there redirects me here again.

I initially wanted to look at the API documentation because I wanted to do something similar to what is mentioned here: https://github.com/electron/electron-packager/issues/743#issuecomment-340656467, but alas that link led me to this never ending annoyance.

So where is the API documentation? Also I request that these links please be fixed.

**Comment by malept** [comment]
Click on "electronPackager" in the right sidebar. Typedoc (the documentation generator we use) pulls in the repository's README.

**Comment by LoLei** [comment]
That did not occur to me. Not very obvious. But I guess I could have clicked on more random places. Thanks nonetheless.

**Comment by malept** [comment]
I've also edited my comment there to point to the API docs as they looked at the time that comment was written.

**Comment by LoLei** [comment]
Nice, yeah I could've looked back in time as well and check out the version history of [api.md](https://github.com/electron/electron-packager/blob/v9.1.0/docs/api.md).
