### ISSUE TITLE
ignore regexp not working as expected.

### ISSUE THREAD

**Issue by trusktr** [electron/electron-packager#1161]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  14.2.1

### Expected Behavior

Ability to ignore all except a certain folder or file.

For example,

```js
/\/home\/trusktr\/src\/project\+two\/(?!dist|node_modules|package\.json)/g
```

### Actual Behavior

All files are included, instead of only a few.

### Additional Information

It seems that electron-packager expects a full match (or something?), which isn't helpful. The reason I believe this is happening (without looking at the source) is because I have thoroughly tested my expressions on http://regexr.com and am confident they should work, but they don't.

Here is an example including the expression and a test input string: https://regexr.com/57ajb

In that example, notice that a call to `str.match(regex)` would return truthy only for the lines that have the blue highlights.

To verify, you can also try this in console:

```js
!!'/home/trusktr/src/project+two/.editorconfig'.match(/\/home\/trusktr\/src\/project\+two\/(?!dist|node_modules|package\.json)/g)
> true (ignored)
!!'/home/trusktr/src/project+two/dist/foo.js'.match(/\/home\/trusktr\/src\/project\+two\/(?!dist|node_modules|package\.json)/g)
> false (not ignored)
```

In practice, this is not working in electron-packager. It seems as if electron-packager expects the entire line to match, not just part of it (or something?), which prevents making such useful expressions.

### workaround

As a workaround, I can list all the top level things to ignore manually, like this:

```js
ignore: [
      /\/home\/trusktr\/src\/project\+two\/(.editorconfig|scripts|.vscode|.gitignore|setup.sh|.prettierrc|.npmrc|etc)/g
]
```

**Comment by trusktr** [comment]
Oops, sorry, the listed workaround above also does not work!

Here is a regexr example showing how it should work: https://regexr.com/57al7

However, nothing is ignored, and everything is included.

What I can do to get it to work, is write it like this, which I am afraid is not robust:

```
ignore: [
      /\/(.editorconfig|scripts|.vscode|.gitignore|setup.sh|.prettierrc|.npmrc|etc)/g
]
```

**Comment by trusktr** [comment]
Note, I am using electron-packager as an indirect dependency of electron-forge. Could that have something to do with it?

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?
