### ISSUE TITLE
Invalid `OsxNotarizeOptions` type

### ISSUE THREAD

**Issue by ffflorian** [electron/electron-packager#1162]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 15.0.0
* **Electron Version:**
  * none
* **Operating System:**
  * Debian 10
* **Last Known Working Electron Packager version:**:
  * `@types/electron-packager 14.0.0`

### Expected Behavior
The type defintions for `electronPackager.Options.osxNotarize` allows the options documented in [`electron-notarize`](https://github.com/electron/electron-notarize#method-notarizeopts-promisevoid).

### Actual Behavior
The type defintions for `electronPackager.Options.osxNotarize` only allow `ascProvider`:

![image](https://user-images.githubusercontent.com/5497598/86029316-50357300-ba33-11ea-96f2-abe72bda52f1.png)

### To Reproduce
Sample code:

```ts
import * as electronPackager from "electron-packager";

const packagerConfig: electronPackager.Options = {
  dir: "test",
  osxNotarize: {
    appleId: "id",
    appleIdPassword: "password",
  },
};
```

### Additional Information
TypeScript's `Omit<>` is used in [`index.d.ts`](https://github.com/electron/electron-packager/blob/master/src/index.d.ts) and this is probably the issue:

```ts
type OsxNotarizeOptions = Omit<NotarizeOptions, 'appBundleId' | 'appPath'>;
```

**Comment by malept** [comment]
Do you mind making a pull request to fix this?

**Comment by ffflorian** [comment]
> Do you mind making a pull request to fix this?

Unfortunately I also don't know how to fix this. I tried a few things but they didn't work 😕
