### ISSUE TITLE
electron-packager skips or ignores the content of package.json

### ISSUE THREAD

**Issue by Yuri6037** [electron/electron-packager#1174]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
Electron Packager 15.1.0
Node v10.19.0
Host Operating system: linux 5.4.0-7642-generic (x64)

* **Electron Version:**
v10.1.0

* **Operating System:**
Linux x86_64

* **Last Known Working Electron Packager version:**:
Not applicable.

### Expected Behavior
Electron packager should not ignore the build options present in package.json.

### Actual Behavior
It ignores everything and just operates a raw cp.

### To Reproduce

```
{
    "name": "test-electron-react-ts",
    "version": "1.0.0",
    "description": "Test app",
    "build": {
        "files": [
            {
                "from": "dist/release",
                "to": ".",
                "filter": ["**/*"]
            }
        ]
    },
    "main": "main.js",
    "scripts": {
        "build:dev": "webpack --config ./webpack/main.config.js",
        "build": "webpack --config ./webpack/package.config.js",
        "internal:wp": "webpack-dev-server --config ./webpack/react.config.js",
        "internal:electron": "electron dist/debug/main.js",
        "start:dev": "parallelshell -k \"npm run internal:wp\" \"npm run internal:electron\"",
        "start": "npm run build:dev && npm run start:dev",
        "lint": "eslint src webpack"
    },
    "keywords": [],
    "author": "",
    "license": "ISC",
    "devDependencies": {
        "@types/react": "^16.9.48",
        "@types/react-dom": "^16.9.8",
        "@typescript-eslint/eslint-plugin": "^3.10.1",
        "@typescript-eslint/parser": "^3.10.1",
        "css-loader": "^4.2.2",
        "electron": "^10.1.0",
        "electron-packager": "^15.1.0",
        "eslint": "^7.7.0",
        "eslint-plugin-react": "^7.20.6",
        "file-loader": "^6.0.0",
        "html-webpack-plugin": "^4.3.0",
        "parallelshell": "git+https://github.com/Yuri6037/parallelshell.git",
        "react": "^16.13.1",
        "react-dom": "^16.13.1",
        "style-loader": "^1.2.1",
        "ts-loader": "^8.0.3",
        "typescript": "^4.0.2",
        "webpack": "^4.44.1",
        "webpack-cli": "^3.3.12",
        "webpack-dev-server": "^3.11.0"
    },
    "dependencies": {}
}
```

**Comment by Yuri6037** [comment]
When replacing electron-packager with electron-builder and building linux AppImage it works

**Comment by malept** [comment]
The `build` key in your `package.json` is a non-standard field. Electron Packager is configured using either the JavaScript API or command line flags. If you would like to use Electron Packager with configuration embedded in `package.json`, take a look at [Electron Forge](https://www.electronforge.io), which uses Electron Packager internally.
