### ISSUE TITLE
App not finding csv files when packaged with electron-packager

### ISSUE THREAD

**Issue by danielrousseaug** [electron/electron-packager#1177]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details
OS: Windows 10 & MacOS
Electron/NodeJS/Electron-Packager: Latest

I am creating a simple app that has all of its files, including csv files for data storage, in its root directory. When running using ```npm start``` the app has no issues and loads the csv files. When I compile using ```electron-packager . (appname)``` however, the files do not load, and the console logs
```
Uncaught Error: ENOENT: no such file or directory, open 'notedb.csv'
    at Object.openSync (fs.js:462)
    at Object.func [as openSync] (electron/js2c/asar.js:140)
    at Object.readFileSync (fs.js:364)
    at Object.fs.readFileSync (electron/js2c/asar.js:542)
    at shownotes (notes.js:59)
    at notes.html:60
handleErrorFromBinding @ internal/fs/utils.js:233
openSync @ fs.js:462
func @ electron/js2c/asar.js:140
readFileSync @ fs.js:364
fs.readFileSync @ electron/js2c/asar.js:542
shownotes @ notes.js:59
(anonymous) @ notes.html:60
```
on both MacOS and Windows 10

At first I thought the packager ignored the files, but when checking `<appname>-win-32-x64/resources/app` I can confirm all of the files were there, yet the error persists. 

### To Reproduce
Create main.js and data.csv in root directory, use fs to read data.csv in main.js, use `npm start` the make sure there are no errors, then use ```electron-packager . <appname>``` and open the app to see error message.

**Comment by malept** [comment]
This is a [frequently asked question](https://github.com/electron/electron-packager/blob/v15.1.0/docs/faq.md#why-isnt-the-relative-path-in-my-app-code-working) ("Why isn't the relative path in my app code working?").

**Comment by danielrousseaug** [comment]
Forgive my ignorance as I'm new to programming, but how would I change
```var rawdata = fs.readFileSync('notedb.csv');```
to read the file if both the js file and the csv file are in the same directory

**Comment by malept** [comment]
```javascript
const path = require('path');
let rawdata = fs.readFileSync(path.join(__dirname, 'notedb.csv'));
```

If you need more assistance, please use one of the [community forums](https://electronjs.org/community).

**Comment by danielrousseaug** [comment]
Perfect, thank you very much!
