### ISSUE TITLE
Add package-lock.json and yarn.lock to the default ignore list

### ISSUE THREAD

**Issue by pushkin-** [electron/electron-packager#1180]
### Preflight Checklist
* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:** 14.2.1
* **Electron Version:** 9.0.4
* **Operating System:** Windows 10
* **Last Known Working Electron Packager version:**: n/a

### Expected Behavior
I expect that the electron packager exclude the package.json and package-lock.json files

### Actual Behavior
Whiles are bundled in the app.asar file.

Is this expected behavior? Should those be excluded from the bundled app? It doesn't seem useful for them to be there.

**Comment by pushkin-** [comment]
@malept  Thanks for tagging this. Should package.json also be on the ignore list?

**Comment by malept** [comment]
> Should package.json also be on the ignore list?

No. `package.json` is used in Electron internals and API such as [`app.getName()`](https://www.electronjs.org/docs/api/app#appgetname) and [`app.getVersion()`](https://www.electronjs.org/docs/api/app#appgetversion).

**Comment by malept** [comment]
Fixed in #1182.
