### ISSUE TITLE
use asar parameter to build app, but cannot start BrowserRunner.js in app.asar 

### ISSUE THREAD

**Issue by ss7424Refar** [electron/electron-packager#1181]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:** 15.1.0
* **Electron Version:** 10.1.2
* **Operating System:** Ubuntu 18.04 x64

### Expected Behavior
can start BrowserRunner.js in app.asar

### To Reproduce
```
git clone https://github.com/ss7424Refar/top-news.git
cd top-news
npm install
npm run build-linux

cd top-news/c/top-news-linux-x64/
./top-news   # start App
```

### Additional Information
1. i use `npm run build-linux-n` without `asar` can start myApp. so it's a question that i wanna know why?
2. `BrowserRunner.js` is the one file of `puppeteer`. i think. 
3. ![error output](https://user-images.githubusercontent.com/33996924/94756047-0315c400-03c9-11eb-906e-450a5e9b458d.png)

**Comment by malept** [comment]
This is unlikely a bug with Electron Packager. I suspect that the puppeteer module doesn't work very well with `asar` and its virtual file system. You probably want to use the [`asar.unpackDir` option](https://electron.github.io/electron-packager/v15.1.0/interfaces/electronpackager.options.html#asar) with the `node_modules/puppeteer` folder.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community).

**Comment by ss7424Refar** [comment]
Hi! 

I tried to use
 `electron-packager ./ --out ./c --platform=linux --arch=x64 --overwrite --icon=icon.ico --asar.unpackDir=node_modules/puppeteer`

or `asar pack app app.asar --unpack node_modules/puppeteer`

or  `electron-packager ./ --out ./c --platform=linux --arch=x64 --overwrite --icon=icon.ico --asar.unpackDir=node_modules`

MyApp still didn't work . I think this dependence may be complicated. but it's fine. i will pack it without `asar`.

Thanks.
