### ISSUE TITLE
`afterPrune` and `afterCopy` callback functions are not called

### ISSUE THREAD

**Issue by jameshfisher** [electron/electron-packager#1185]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:** 15.1.0
* **Electron Version:** v10.1.3
* **Operating System:** darwin 19.6.0 (x64)

### Expected Behavior

`afterExtract`, `afterPrune` and `afterCopy` functions are called as a result of a call to `packager`.

### Actual Behavior

Only the `afterExtract` function is called; the `afterPrune` and `afterCopy` functions are not called:

```
$ node build.js
Packaging app for platform darwin x64 using electron v10.1.3
afterExtract /var/folders/7g/m6tkc5n56l7ds_6dyr28jvb00000gn/T/electron-packager/darwin-x64-template 10.1.3 darwin x64 [Function (anonymous)]
```

### To Reproduce
See [this branch of this repo](https://github.com/jameshfisher/electron-packager-example/tree/hook-functions-not-called) for minimal example, with a build script that looks like:

```js
#!/usr/bin/env node
const packager = require("electron-packager");
(async () => {
  const appPaths = await packager({
    dir: '.',
    name: 'MyElectronApp',
    overwrite: true,
    prune: true,
    afterExtract: [(buildPath, electronVersion, platform, arch, callback) => {
      console.log("afterExtract", buildPath, electronVersion, platform, arch, callback);
    }],
    afterPrune: [(buildPath, electronVersion, platform, arch, callback) => {
      console.log("afterPrune", buildPath, electronVersion, platform, arch, callback);
    }],
    afterCopy: [(buildPath, electronVersion, platform, arch, callback) => {
      console.log("afterCopy", buildPath, electronVersion, platform, arch, callback);
    }]
  });
  console.log(`Electron app bundles created: ${appPaths.join("\n")}`);
})();
```

**Comment by jameshfisher** [comment]
Context: I'm looking for a way to work around [this bug](https://github.com/electron/electron-packager/issues/1184) by overwriting the `package.json` that electron-packager generates. But I don't know of a reliable way to identify the `package.json` to overwrite, considering that electron-packager can build for many different platforms, which have different file structures.

**Comment by malept** [comment]
[Hook functions](https://electron.github.io/electron-packager/v15.1.0/modules/electronpackager.html#hookfunction) are callback based, as per the documentation you need to call `callback()` when you're done.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community).

**Comment by jameshfisher** [comment]
A _ha_, thanks @malept! I see now that I was blocking the whole build process by not calling `callback`.

I think a small example would help in the docs for HookFunction - would it be helpful if I contributed one?

**Comment by malept** [comment]
I added a link to the Electron Packager plugins from the `HookFunction` docs: https://github.com/electron/electron-packager/commit/3e2ecec883e8c6438b01d95c4d4135660b62957c
