### ISSUE TITLE
Codesign succeeds but triggers "WARNING: Code sign failed; please retry manually" (also notarization fails silently)

### ISSUE THREAD

**Issue by felixfaire** [electron/electron-packager#1197]
* [ x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

Using --osx-sign triggers a signing failed warning but codesign -dv on the app indicates the the app was in fact signed. This error also seems to stop the notarization process as using the CLI arguments as per the documentation results in no notarization process (and there is no concise documentation or example of how to use this feature correctly).

The npm command i am using is the following:
```"NODE_ENV=production DEBUG=electron-packager electron-packager . --out=build --icon=[my-iconpath] --prune=true --hardenedRuntime --osx-sign --osx-sign.identity='Developer ID Application: [my-id]' --osx-sign.entitlements='./build/entitlements/entitlements.plist' --osx-notarize --osx-notarize.appleId='[my-appleId]' --osx-notarize.appleIdPassword='[my-password]' --overwrite --app-bundle-id=[my-bundleid]"```

* **Electron Packager Version:**
15.1.0
* **Electron Version:**
11.0.3
* **Operating System:**
macOS 10.15.7

### Expected Behavior
Output indicates code signing was successful and begins notarization process.

### Actual Behavior
electron-packager outputs an error about "WARNING: Code sign failed; please retry manually [...] rejected source=Unnotarized Developer ID" (which as far as I can tell doesn't make sense as apps are notarized not developer ID's..). Then the --osx-notarize arguments seem to fail silently as there is no further output and it is unclear whether --osx-notarize has done anything.

Please let me know if there is an error or misunderstanding in my use of these CLI arguments, however I have done my best to read the minimal documentation of these features, and gauge what the expected output should be.

### Additional Information
console output (removed app information with []):

```
electron-packager Running electron-osx-sign with the options {"0":true,"1":{"identity":"Developer ID Application: [my-id]"},"2":{"entitlements":"./build/entitlements/entitlements.plist"},"platform":"darwin","app":"/var/folders/j0/sw3l2jkn2_qgzwrvbsgp8ldh0000gn/T/electron-packager/darwin-x64/[my-app]-x64/[my-app].app","version":"11.0.3"} +12ms
WARNING: Code sign failed; please retry manually. Error: Command failed: spctl --assess --type execute --verbose --ignore-cache --no-cache /var/folders/j0/sw3l2jkn2_qgzwrvbsgp8ldh0000gn/T/electron-packager/darwin-x64/[my-app]-darwin-x64/[my-app].app
/var/folders/j0/sw3l2jkn2_qgzwrvbsgp8ldh0000gn/T/electron-packager/darwin-x64/[my-app]-darwin-x64/[my-app].app: rejected
source=Unnotarized Developer ID
```

output of codesign -dv on the app:
```
Executable=[my-path-to-app]
Identifier=[my-app-bundle-id]
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=1785 flags=0x0(none) hashes=50+3 location=embedded
Signature size=9052
Timestamp=10 Dec 2020 at 13:18:42
Info.plist entries=25
TeamIdentifier=[my-team-id]
Sealed Resources version=2 rules=13 files=13514
Internal requirements count=1 size=188
```

**Comment by felixfaire** [comment]
I have tried several permutations of arguments for the CLI command and now have a message about notarization failing. However it says no appleId was provided when i have provided it as described in the docs. Is there any example of how to use the notarization commands from the command line as it seems impossible to sign and notarize an app with a single CLI command. (if this is impossible it should be made clear in the docs).

```
WARNING: Failed validation, notarization will not run: No authentication properties provided (e.g. appleId, appleApiKey)
``` 

CLI Command:
```
"pack:macos": "NODE_ENV=production DEBUG=electron-packager electron-packager . --out=build --icon=build/icons/[app].icns --prune=true --osx-sign.hardenedRuntime=true --osx-sign.identity='Developer ID Application: Felix Faire ([my-id])' --osx-sign.entitlements-inherit=./build/entitlements/entitlements.plist --osx-notarize.appleId='[my-apple-id]' --osx-notarize.appleIdPassword='[app-specific-password]' --overwrite --app-bundle-id=[bundle-id]",
```

**Comment by felixfaire** [comment]
If anyone else is having issues with notarization and electron-packager i'd recommend just following this process manually.

http://www.zarkonnen.com/signing_notarizing_catalina

**Comment by felixfaire** [comment]
I don't consider this issue closed. The suggested actions and arguments for signing and notarization with electron-packager did not work and i had to use a manual workaround. I used exactly the same apple ids, app-specific-passwords etc with altool and codesign so I presume there is still a bug in electron-packager or electron-notarize resulting in these errors.

**Comment by malept** [comment]
Unfortunately, due to the limited amount of time of the maintainers and the limited amount of information present in this issue, we cannot help debug your app at this time. Instead, consider using one of the [community forums](https://electronjs.org/community), as there are more people there available to answer questions.

**Comment by felixfaire** [comment]
I understand, and am grateful for all open source efforts on electron-packager and other tools. My application doesn't need debugging, it signed and notarized fine with the apple tools. However I wasted a lot of time trying to get the advertised signing and notarization functionality working with electron-packager, so there should probably be an open issue that the CLI for signing and notarization workflow has problems.

**Comment by malept** [comment]
The [Electron docs](https://www.electronjs.org/docs/tutorial/code-signing#electron-packager) provide a working API example of code signing with Electron Packager which should be fairly straightforward to convert to CLI flags (although I would recommend given the complexity of code signing/notarization, it's better to just write a Node script than try to deal with all of the CLI flags in one very long line).

If you're having an issue with notarization, it's probably better to file an issue with `electron-notarize` as for the most part, Electron Packager forwards the configuration directly to that module.

**Comment by felixfaire** [comment]
That link you showed was my starting point for these required arguments. 

"I would recommend given the complexity of code signing/notarization, it's better to just write a Node script than try to deal with all of the CLI flags in one very long line"

A note like this in the docs would have been invaluable at the start of this process. I am primarily a native / graphics developer so less comfortable with the many different ways to get node scripts to do what i need. I will avoid the cli commands approach for more complex tasks like this in the future.

Thanks for your input in any case.
