### ISSUE TITLE
Using asar hangs with Node.js between 15.2.0 and 15.4.0

### ISSUE THREAD

**Issue by ryankashi** [electron/electron-packager#1198]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 15.2.0
* **Electron Version:**
  * 9.2.0
* **Operating System:**
  * MacOS Big Sur virtual machine running on Windows 10
* **Last Known Working Electron Packager version:**:
  * 15.2.0

### Expected Behavior
Electron-packager successfully packages my application like it normally would

### Actual Behavior
Electron-packager is hanging during the "Packaging Application" step

### To Reproduce
After installing socket.io-client on my virtual machine, I started running into issues regarding packaging of my application via npm run make. I'd say about 99/100 times it will hang on the "Packaging Application" step of the packaging process, however once in a blue moon it will actually work (I have no idea why). I have added a picture of my log as well.

Even after uninstalling socket.io-client, I continue to have this same issue so I believe the two may be unrelated.

Electron-packager hangs on Packaging Application

### Additional Information
[
![electron_packager_hanging](https://user-images.githubusercontent.com/13973467/102145422-08a57680-3e1c-11eb-81e4-d23f92480d71.png)
](url)

**Comment by malept** [comment]
It would help if you could run DEBUG='*' npm run make and post the output in a gist.

**Comment by ryankashi** [comment]
`} +3ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules +5ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/@babel +10ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/@electron +9ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/@electron-forge +7ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/@jimp +8ms
⠹ Preparing native dependencies  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/@malept +115ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/@sindresorhus +8ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/@szmarczak +7ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/@types +27ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/@videojs +9ms
⠸ Preparing native dependencies  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/@videojs/xhr/node_modules +13ms
⠴ Preparing native dependencies  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/electron-squirrel-startup/node_modules +167ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/engine.io-client/node_modules +17ms
⠧ Preparing native dependencies  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/make-dir/node_modules +211ms
⠏ Preparing native dependencies  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/pid-from-port/node_modules +158ms
⠋ Preparing native dependencies  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/process-exists/node_modules +59ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/qrcode/node_modules +22ms
⠹ Preparing native dependencies  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/socket.io-client/node_modules +150ms
⠸ Preparing native dependencies  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/socket.io-parser/node_modules +46ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/taskkill/node_modules +17ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/temp-write/node_modules +17ms
⠼ Preparing native dependencies  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/xhr/node_modules +51ms
  electron-rebuild scanning: /private/var/folders/mm/bpn8c25s3y79jx7rh6f8czd00000gn/T/electron-packager/darwin-x64/tenami-darwin-x64/Electron.app/Contents/Resources/app/node_modules/xml2js/node_modules +19ms
✔ Preparing native dependencies
⠋ Packaging Application  electron-forge:hook hook triggered: readPackageJson +1s
  electron-forge:hook hook triggered: packageAfterPrune +2ms
  electron-packager Running asar with the options {} +10s
⠼ Packaging Application
`

The output was extremely long, but this was at the tail end of it. Although I am not quite sure what a gist is if this is not the form that you wanted it in?

**Comment by ryankashi** [comment]
![packager_hanging_2](https://user-images.githubusercontent.com/13973467/102147026-e52ffb00-3e1e-11eb-84fc-a4fce498fecb.png)

**Comment by malept** [comment]
It would be be good to know if it works on macOS Big Sur, in a physical Mac.

**Comment by nathanlesage** [comment]
Oh, hello! I've encountered the same problem, but on Intel Big Sur. I have already followed the problem quite some time. Here's what I figured:

- When running normally, electron-packager (used with electron-forge in my case) hangs on the Packaging-part
- However, whenn running with the DEBUG environment, it simply silently exits with no error after running asar with `{}`-options (no file generated)
- Getting to the root of the problem I figured that the last promise of packaging a file into the asar-archive is never resolved, hence an infinite loop, as electron-packager waits for this to be resolved. So everything works out until the asar-packager should close the write stream.
- Setting `asar: false` (in my case in electron-forge) resolves this problem, and everything works as expected.

**Comment by malept** [comment]
What version of Node.js is being used to run Electron Forge?

**Comment by nathanlesage** [comment]
On my machine it's on `15.3.0`, the GitHub actions use 12 (`lts/erbium`). I do have to say that I did not try it out on the CI, it may be that it's also a problem with node (?)

**Comment by malept** [comment]
> On my machine it's on `15.3.0`, the GitHub actions use 12 (`lts/erbium`). I do have to say that I did not try it out on the CI, it may be that it's also a problem with node (?)

Does it hang on versions of Node.js earlier than 15.2.0?

**Comment by nathanlesage** [comment]
Running electron-packager via electron-forge, `asar: true`, checked using only the node releases supported via [Homebrew](https://brew.sh/) (e.g. lts 12 and 14, as well as the current 15.3.0):

- ✅  node `v12.20.0` both with `DEBUG='*'` and without
- ✅  node `v14.15.2` both with `DEBUG='*'` and without
- ⛔️  node `v15.3.0` both with `DEBUG='*'` (exits without emitting binaries) and without (hangs on infinite loop)

So this does indicate a problem introduced with node 15. Is there a specific reason why you asked for 15.2, or was this just a typo?

**Comment by malept** [comment]
> So this does indicate a problem introduced with node 15. Is there a specific reason why you asked for 15.2, or was this just a typo?

It's likely [this bug](https://github.com/electron/asar/issues/210).

**Comment by nathanlesage** [comment]
Ah, I see. Yes, this makes sense. Thank you!

**Comment by malept** [comment]
Per the discussion and linked bug, this is a bug in Node.js itself, between versions 15.2.0 and 15.4.0. The fix was released in Node.js 15.5.0.
