### ISSUE TITLE
"Uncaught Exception: Error: Cannot find module" or "Segmentation fault"

### ISSUE THREAD

**Issue by tatsujb** [electron/electron-packager#1210]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
Electron Packager 15.2.0
Node v14.15.4
Host Operating system: linux 5.8.0-40-generic (x64)

* **Electron Version:**
v11.2.1

* **Operating System:**
Ubuntu 20.10 64bit

### Expected Behavior
a usable binary

### Actual Behavior
I run : `electron-packager . --overwrite`

the compile happens

I go into the created folder and run the binary with terminal

it crashes at launch with 
```
Uncaught Exception: Error: Cannot find module
```
...whatever the first loaded module in the list is.

or with : 
```
Segmentation fault
```

The compile is ultra fast it seems to ignore bundling the node_modules with the app.

### To Reproduce

on ubuntu 20.10 64bit, run : 
```
mkdir my-electron-app && cd my-electron-app
npm init -y
npm i --save-dev electron
```
edit package.json to have `"start": "electron ."` inside scripts
create a basic main.js : 
```
'use strict';
const { app, BrowserWindow } = require('electron')
require('@electron/remote/main').initialize()

function createWindow () {
  const win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      enableRemoteModule: true,
      nodeIntegration: true
    }
  });
  win.loadFile('index.html')
  win.webContents.openDevTools() 
}

app.whenReady().then(createWindow)

app.on('ready', () => {
  createWindow
});

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})
```
and index.html : 
```
<!DOCTYPE html> 
<html> 
  <head> 
    <meta charset="UTF-8"> 
    <title>app</title>
    <meta http-equiv="Content-Security-Policy" 
          content="script-src 'self' 'unsafe-inline';" /> 
  </head> 
  <body> 
     <div>stuff</div>
  </body> 
</html> 
```
check that it runs with : 
```
npm start #or electron .
```

compile : 
```
electron-packager . --overwrite
```

**Comment by malept** [comment]
I don't think this is a bug in Electron Packager. You appear to be missing `@electron/remote` from your `dependencies`.
