### ISSUE TITLE
platform/arch combination mas/arm64 is not supported

### ISSUE THREAD

**Issue by DanielLeberle** [electron/electron-packager#1214]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 15.2.0
* **Electron Version:**
  * 11.2.1
* **Operating System:**
  * macOS 10.15.7
* **Last Known Working Electron Packager version:**:
  * I never tried the mas/arm64 combination before

### Expected Behavior
As stated in the release notes to electron-packager 15.1.0 the combination mas/arm64 should be possible

### Actual Behavior
When trying to run electron-packager with the combination, I get the warning
`WARNING: The platform/arch combination mas/arm64 is not currently supported by Electron Packager`

This is how I call the electron-packager:
```"electron-packager . --appname=MYAPP --app-bundle-id=com.my.app --electron-version=11.2.0 --overwrite --platform=mas --arch=arm64 --icon=resources/Icon.icns --prune --out=../mas-distribution --app-version=2.3.10 --build-version=$(curl -s https://increment.build/com.my.app) --extend-info=../extendedInfo.plist --ignore=^/build_scripts"```

**Comment by malept** [comment]
I can't reproduce this. My steps:

1. `git clone https://github.com/electron/electron-quick-start && cd electron-quick-start`
2. `npm install --save-dev electron-packager`
3. `node_modules/.bin/electron-packager . --platform=darwin --arch=arm64` _(**Note**: in a real project this should be an [npm script](https://docs.npmjs.com/cli/v6/using-npm/scripts), but this is easier for repro steps.)_

Output:

```
Packaging app for platform mas arm64 using electron v11.2.1
WARNING: signing is required for mas builds. Provide the osx-sign option, or manually sign the app later.
Wrote new app to /tmp/electron-quick-start/electron-quick-start-mas-arm64
```
----

What is the output when you run `electron-packager --version`?

**Comment by DanielLeberle** [comment]
Thanks for your time!

This is the output:
`Electron Packager 15.2.0
Node v14.0.0
Host Operating system: darwin 19.6.0 (x64)`

You are using `platform=darwin` shouldn't this be `mas` when I want to build for the Mac app store?

Or do I have to change it to `darwin` since I have an intel Mac?

**Comment by malept** [comment]
> You are using `platform=darwin` shouldn't this be `mas` when I want to build for the Mac app store?

Sorry, I typoed in the repro steps. I fixed it in the above comment. The output is copy/pasted from my terminal, though.

Can you try the repro steps above and see if they work for you?

**Comment by DanielLeberle** [comment]
Thanks for your help, I tried your steps to reproduce and it works as you said. So the problem is on my setup!
