### ISSUE TITLE
Packing for Windows with --asar does nothing

### ISSUE THREAD

**Issue by luquezsantiago86** [electron/electron-packager#1223]
If I run the packager without the option --asar, it works perfectly and it creates the dist-folder.

But if I run it with --asar option, it says:

Packaging app for platform win32 ia32 using electron v11.2.0

But I never recieve the message:

Wrote new app to release-builds\electron-tutorial-app-win32-ia32

And I dont even get an error message.

How can I see if there is an error here?

**Comment by mistermaeks** [comment]
Hi, i have the issue that the package (arch=ia32) is done, but if i start it just a white screen appears.
It works with arch=x64. My electron version: 12.0.1, electron-packager: 15.2.0. I have no error in the console if i enable webdevtools.

**Comment by malept** [comment]
There's not enough information to go on here. If the behavior still occurs, please provide the following in a new comment:

* Electron Packager version

* Operating system and version

* Architecture of the computer you're running this on (the console output of `node -e "console.log(process.arch)"`)

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.

* What are the exact command line arguments are you passing?

* Please provide either a failing minimal testcase (with code) or detailed steps to reproduce your
problem. Using [electron-quick-start](https://github.com/electron/electron-quick-start) is a good starting point.
