### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by justinjc** [electron/electron-packager#1225]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

The link https://electronjs.org/docs/tutorial/application-packaging/ mentioned in https://github.com/electron/electron-packager/blob/master/src/index.d.ts is a 404. Is there a better link to use instead here?

**Comment by malept** [comment]
Fixed in https://github.com/electron/electron-packager/commit/e2d317f0a7906e08dc8744fb78cca4ecc486166a
