### ISSUE TITLE
Support Apple Silicon Universal

### ISSUE THREAD

**Issue by h3poteto** [electron/electron-packager#1226]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description
Now I can build mas/arm64 package using `--arch=arm64`. But I want to build `universal` package.

### Proposed Solution
Add `universal` as `arch` parameter, and build `universal` Electron package. Refs: https://github.com/electron/universal

### Additional Information
See also https://github.com/electron/electron/issues/26710

**Comment by malept** [comment]
I'm generally not inclined to add support for this in Electron Packager itself. Adding a `universal` arch to Electron Packager would make the complexity of this Node.js module increase significantly. My feeling is that `@electron/universal` needs to be a part of the build system after Electron Packager has run. For example _(not tested, partially based on the `@electron/universal` README)_:

```javascript
const glob = require('glob')
const { makeUniversalApp } = require('@electron/universal')
const packager = require('electron-packager')
const path = require('path')


// Assumes support for top-level await, if it doesn't exist for the version of Node.js
// you're using, wrap in an async function.

const commonOptions = { /* common Electron Packager options here */ }

const arm64Path = await packager({
  ...commonOptions,
  platform: 'darwin',
  arch: 'arm64'
})[0]

const x64Path = await packager({
  ...commonOptions,
  platform: 'darwin',
  arch: 'x64'
})[0]

const arm64AppPath = glob.sync(path.join(arm64Path, '*.app'))[0]
const x64AppPath = glob.sync(path.join(x64Path, '*.app'))[0]
const universalApp = path.basename(x64AppPath)

await makeUniversalApp({
  arm64AppPath,
  x64AppPath,
  outAppPath: universalApp,
});
```

**Comment by pushkin-** [comment]
for anyone that stumbles upon this, support was added [here](https://github.com/electron/electron-packager/pull/1346). There is now a `universal` `arch` option that can be used.

**Comment by ofTheo** [comment]
I am running into an issue with arch="universal" where we have a universal binary being included in the app package. 

```
Stitching universal app for platform darwin
Detected file "Contents/Resources/app/app/projectGenerator" that's the same in both x64 and arm64 
builds and not covered by the x64ArchFiles rule: "undefined"
```

Can anyone explain how I can set the variable: `x64ArchFiles` 

I have tried setting it as an arg here, but I am not sure electron-packager is even passing it on to `@electron/universal`? 

`"build:macos": "electron-packager . $npm_package_productName --icon=static/icon/of.icns --out=dist --ignore='dist' --ignore='readme.md' --prune --overwrite --electron-version=24.1.2 --platform=darwin --arch=universal --x64ArchFiles=Contents/Resources/app/app/projectGenerator"`

Or what is the correct way to pass `osxUniversal` options via a build command ( this is in our package.json ) 

`"build:macos": "electron-packager . $npm_package_productName --icon=static/icon/of.icns --out=dist --ignore='dist' --ignore='readme.md' --prune --overwrite --electron-version=24.1.2 --platform=darwin --arch=universal --osxUniversal={x64ArchFiles:'Contents/Resources/app/app/projectGenerator'}",`

Or is there any other way I can have the file be included for just one of the builds before they are joined so it doesn't error?

Related: 
https://github.com/electron/universal/pull/47

**Comment by ofTheo** [comment]
so changing this function too:

from:

```
  await universal.makeUniversalApp({
    ...comboOpts.osxUniversal,
    x64AppPath: path.resolve(x64AppPath, appName),
    arm64AppPath: path.resolve(arm64AppPath, appName),
    outAppPath: path.resolve(universalStagingPath, appName)
  })
```

to:
```
  await universal.makeUniversalApp({
    ...comboOpts.osxUniversal,
    //add this line to pass through x64ArchFiles to be excluded from lipo 
    x64ArchFiles : comboOpts.x64ArchFiles,
    x64AppPath: path.resolve(x64AppPath, appName),
    arm64AppPath: path.resolve(arm64AppPath, appName),
    outAppPath: path.resolve(universalStagingPath, appName)
  })
```

allows me to build a universal app by adding the `x64ArchFiles` option to the build:

```
    "build:macos": "electron-packager . $npm_package_productName --icon=static/icon/of.icns --out=dist --ignore='dist' --ignore='readme.md' --prune --overwrite --electron-version=24.1.2 --platform=darwin --arch=universal --x64ArchFiles=Contents/Resources/app/app/projectGenerator",
```

It definitely doesn't feel like an elegant solution, I think there should be a way to do this via `OsxUniversalOptions` but there doesn't seem to be any documentation on how to do that. 

Apologies for the noise also, it is just quite a breaking issue for us, and the documentation here seems lacking.

**Comment by erickzhao** [comment]
Hey @ofTheo,

In the electron-packager config, `osxUniversal` is the actual option name while `OsxUniversalOptions` is the TypeScript type of the object structure. Hope this points you in the right direction!

https://electron.github.io/electron-packager/main/interfaces/electronpackager.options.html#osxuniversal

**Comment by ofTheo** [comment]
Thanks for the reply @erickzhao !

What would be the correct way to get `x64ArchFiles` set via the `osxUniversal` option?

It's quite hard to tell how to pass the variable through though to avoid the error.

Trying:

` "build:macos": "electron-packager . $npm_package_productName --icon=static/icon/of.icns --out=dist --ignore='dist' --ignore='readme.md' --prune --overwrite --electron-version=24.1.2 --platform=darwin --arch=universal  --osxUniversal=x64ArchFiles:Contents/Resources/app/app/projectGenerator"`

Logging the `comboOpts.osxUniversal` 

```
  console.log("universal options are:");
  console.log(comboOpts.osxUniversal);
```

I do see 
```
universal options are:
x64ArchFiles:Contents/Resources/app/app/projectGenerator
```

But I still get the error about:
`not covered by the x64ArchFiles rule: "undefined"` 

I'm sure it must be a formatting issue ( hopefully ), but the only thing that has worked so far is manually adding that line in `universal.js` as in my previous comment. 

Thanks so much!
Theo

**Comment by ofTheo** [comment]
Amazing! 

Thank you @erickzhao - it works!! 
Really appreciate the help.  🙏

> The documentation around this could definitely be clearer, though!

Oh yes, I am guessing a lot of people might run into this. A quick note or example in the docs would definitely be helpful. 

It's a shame it is needed at all as I think the default behavior of `electron/universal` should just be to ignore universal binaries that are identical instead of erroring.  But great we can pass it in here, I can remove my `sed` hack now 😊

**Comment by erickzhao** [comment]
I also opened https://github.com/electron/electron-packager/pull/1533 as I noticed that this was missing from the CLI's `usage.txt`.

Thanks for bringing this up @ofTheo!

**Comment by zinne** [comment]
Does anyone know how to add multiple paths to this arg?
I have tried anything, but it only works with one path. From a yargs perspective I have to add the same arg twice:
`--osxUniversal.x64ArchFiles=Contents/Resources/somefile --osxUniversal.x64ArchFiles=Contents/Resources/otherFile `
but then I got "invalid pattern"
