### ISSUE TITLE
Do not ignore .obj files during packaging

### ISSUE THREAD

**Issue by axeljaeger-arculus** [electron/electron-packager#1237]
This PR https://github.com/electron/electron-packager/pull/491 adds a rule to prevent files with the extension .obj to be included as resources in an electron project. While the rational is understandable, this causes problems for projects that use 3D models store in the Wavefront OBJ file format: https://de.wikipedia.org/wiki/Wavefront_OBJ
Unfortunately, both the windows object files that occur during compilation and those 3D models share the same file extension .obj.

Other people reporting this as well.
- https://stackoverflow.com/questions/42865702/electron-packager-excludes-obj-model-files-in-built-application
- https://github.com/electron-userland/electron-builder/issues/2022 (Relates to electron-builder)

I am unsure how to tackle this problem as I found out no way to switch the behavior at runtime. Just removing the rule again will make some people happy but makes other people suffer who benefited from the original PR.

**Comment by malept** [comment]
Per the [API docs for `ignore`](https://electron.github.io/electron-packager/v15.2.0/interfaces/electronpackager.options.html#ignore), set `ignore` to a [function](https://electron.github.io/electron-packager/v15.2.0/modules/electronpackager.html#ignorefunction) which will not use the default paths for ignoring paths.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).
