### ISSUE TITLE
Portable mac DMG option

### ISSUE THREAD

**Issue by Bug-Reaper** [electron/electron-packager#1242]
### Preflight Checklist

* [ x ] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

It'd be great to have a portable option on mac where the user doesn't have to install the application as an app. This is great for cases where an electron application is used as an assistant for another application.

### Proposed Solution

Create some workflow for portable dmgs that can be run and will immediately launch the electron application rather than requiring the application to be installed.

### Alternatives Considered

Possibly having the user install node and install electron that way with normal pre-compiled binaries? wouldn't be as clean though and then all source code has to be on the device? Or possibly bundle the pre-compiled portable electron binaries with the app?

### Additional Information

This does seem to still be possible. A quick search for portable mac apps will get you links to portable versions of software like chrome and firefox. So possibly there's a way to convert non-portable dmgs to portable apps after the fact. Windows does have a portable option, perhaps similar option could be added to mac.

**Comment by malept** [comment]
DMGs are outside the scope of Electron Packager, which does not generate distributables. You'll probably want [`electron-installer-dmg`](https://github.com/electron-userland/electron-installer-dmg) or [Electron Forge](https://electronforge.io) (which uses `electron-installer-dmg` **and* Electron Packager under the hood).

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).

**Comment by Bug-Reaper** [comment]
Thanks for the heads up @malept ! Much appreciated, that makes total sense :100:
