### ISSUE TITLE
packaged app is unable to locate .node file in electron-forge

### ISSUE THREAD

**Issue by robosushie** [electron/electron-packager#1245]
I have built an application using electron-forge where I have added native Cpp functionality.  The front end part is using react and I am using a webpack script that continuously watches for the changes in the react files 

> "watch": "webpack --config webpack.renderer.js --watch",

and generate a compiled version of the react files into a compiled_renderer.js. I am then adding directly to the HTML file as a script.

> <script src="./compiled/compiled_renderer.js"></script>

I am using electron forge to build and package my project. Initally I was trying to package using asar = true, so that I can hide my code files while transferring the packaged folders to other systems, but the app was not running as the native node addons were getting compiled to a temp folder in windows and the packaged app was trying to reference that location. After a lot of searching and trial testing I tried this modification [Link](https://github.com/electron/electron-packager/issues/740#issuecomment-498686181) in my packager configs

> "forge": {
>             "packagerConfig": {
>                 "asar": {
>                     "unpack": "*.{node,dll}"
>                 }
>             },

and I am using bindings to import the node addon to my app.

> const addon = require('bindings')('libsdr');

On I have packaged the app using the script

> "package": "electron-forge package"

The node is correctly placed in the asar.unpacked folder, and is working correctly in my laptop but when I transferred the entire output folder to another laptop. It is still showing the error.

![image](https://user-images.githubusercontent.com/61646255/120127454-0b830080-c1dd-11eb-9823-81ade54ac2f8.png)

Whereas the file location for the node file is the same which it is trying to reference as shown in the error message.

![image](https://user-images.githubusercontent.com/61646255/120127517-32d9cd80-c1dd-11eb-8ed8-18abf395041f.png)

But when I built the installer using "electron-forge make" and tried to install it on another laptop. After installation, it was again trying to reference the temp folder for the .node file.
Please can anyone help me with this issue? Thanks

**Comment by malept** [comment]
In order to debug your problem further, we need a minimal testcase to reproduce your problem. Using the [`electron-quick-start`](https://github.com/electron/electron-quick-start) repository as a base, could you please create a minimal Electron app that illustrates the issue you described, and post a link to it here?

**Comment by gaoxianglyx** [comment]
same error, any solutions?

**Comment by jparismorgan** [comment]
I believe I'm also running into this and have created a simple test repo here: https://github.com/jparismorgan/electron-forge-napi-pnpm

**Comment by LZQCN** [comment]
The reason for this error may be the .node file cannot find the .dll file in the same directory.
