### ISSUE TITLE
Problem After Move

### ISSUE THREAD

**Issue by meteesen** [electron/electron-packager#1249]
Electron Packager 15.2.0
Node v14.17.1
Host Operating system: win32 10.0.18363 (ia32)
Electron:v13.1.2

### Expected Behavior

I build my project. Its run on Nodejs. I compile this project with Electron-Packager. It's run, but when i move compiled folder, project won't run I get some path errors.

```
 export function getSafeDashPath(): string {
     let home = app.getPath('home');
     home = path.resolve(home, ".SafeDash");
     if (!fs.existsSync(home)) {
         fs.mkdirSync(home);
     }
     return home;
 }
```

![image](https://user-images.githubusercontent.com/86021992/122308205-9883c480-cf14-11eb-99d2-b1c82e0bc70c.png)

**Comment by malept** [comment]
This doesn't sound like a problem with Electron Packager, but rather an issue with how you've configured your Electron app. You either need to:

* Reference Node.js modules only in the main process and use IPC to send the values back to the renderer
* Enable `nodeIntegration` and disable `contextIsolation` on the [BrowserWindow](https://www.electronjs.org/docs/api/browser-window#new-browserwindowoptions) where you want this code to run (which can cause [security issues](https://www.electronjs.org/docs/tutorial/security#2-do-not-enable-nodejs-integration-for-remote-content))

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).

**Comment by meteesen** [comment]
I add NodeIntegration:true and  contextIsolation:false but it is not work still.
