### ISSUE TITLE
How can I set the electron entry script without setting "main" in package

### ISSUE THREAD

**Issue by XfaonAE** [electron/electron-packager#1254]
### Preflight Checklist

* [ x ] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/master/CONTRIBUTING.md) for this project.
* [ x ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ x ] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 
* **Electron Version:** 13
  * 
* **Operating System:**windows 10
  * 
* **Last Known Working Electron Packager version:**: latest
  * 

### Expected Behavior

How can i tell electron-packager to use a custom entry script without setting it in "main"

**Comment by malept** [comment]
This is a limitation of Electron itself, it's required to set the entry script in the `main` key of your package.json file.

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron). This issue tracker is for bugs and feature requests only, not questions about how to use Electron Packager.

**Comment by XfaonAE** [comment]
Isn't electron-packager doign the packaging, I want to be able to tell electron-packager to use a different main script, not electron

**Comment by malept** [comment]
Edit the `package.json` script before running Electron Packager, I guess. Anyway, this is a usage question and not a bug or feature,

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).

**Comment by XfaonAE** [comment]
Hmm not a bad idea, thanks!
