### ISSUE TITLE
App icon not showing in Linux

### ISSUE THREAD

**Issue by AlyArman07** [electron/electron-packager#1272]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 
* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron Packager version:**:
  *

**Comment by malept** [comment]
See the [FAQ](https://github.com/electron/electron-packager/blob/v15.3.0/docs/faq.md#how-do-i-set-an-icon-on-linux).

If you need more assistance, please use one of the [community forums](https://electronjs.org/community), including the [Electron Discord server](https://discord.gg/electron).
