### ISSUE TITLE
Configuration Not Passed to Electron Notarize

### ISSUE THREAD

**Issue by tubbo** [electron/electron-packager#1286]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 15.4.0
* **Electron Version:**
  * 15.0.0
* **Operating System:**
  * macOS 11.3
* **Last Known Working Electron Packager version:**:
  * 15.3.0

### Expected Behavior

When upgrading to `electron-packager` v15.4, I expected my `electron-notarize` configuration to be passed onward toward that library for proper macOS notarization.

### Actual Behavior

Notarization fails because it can't find some configuration:

```
 Checking your system
✔ Checking your system
- Resolving Forge Config
✔ Resolving Forge Config
- Preparing to Package Application for arch: x64
We need to package your application before we can make it
- Compiling Main Process Code
✔ Compiling Main Process Code
- Compiling Renderer Template
✔ Compiling Renderer Template
- Compiling Renderer Preload: main_window
✔ Compiling Renderer Preload: main_window
✔ Preparing to Package Application for arch: x64
- Preparing native dependencies
✔ Preparing native dependencies
- Packaging Application
WARNING: Code sign failed; please retry manually. Error: No identity found for signing.

An unhandled rejection has occurred inside Forge:
Error: The appleId property is required when using notarization with appleIdPassword
    at Object.validateLegacyAuthorizationArgs (/Users/runner/work/nerdst/nerdst/node_modules/electron-notarize/src/validate-args.ts:36:13)
    at authorizationArgs (/Users/runner/work/nerdst/nerdst/node_modules/electron-notarize/src/legacy.ts:17:16)
    at Object.<anonymous> (/Users/runner/work/nerdst/nerdst/node_modules/electron-notarize/src/legacy.ts:58:10)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/runner/work/nerdst/nerdst/node_modules/electron-notarize/lib/legacy.js:4:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

The same code works when you pin `electron-packager` to v15.3.0, and my `electron-notarize` version did not change when I pinned this dependency.

### To Reproduce

Install `electron-notarize` alongside `electron-packager`, and use the following config:

```javascript
{
    asar: true,
    icon: './src/icons/app.icns',
    extraResource: ['./src/sounds/myproject.aif'],
    osxSign: {
      identity: process.env.APPLE_DEVELOPER_IDENTITY,
      'hardened-runtime': true,
      entitlements: 'etc/entitlements.plist',
      'entitlements-inherit': 'etc/entitlements.plist',
      'signature-flags': 'library',
      'gatekeeper-assess': false,
    },
    osxNotarize: {
      appBundleId: 'com.myproject.app',
      ascProvider: '[REDACTED]',
      appleId: process.env.APPLE_ID,
      appleIdPassword: process.env.APPLE_PASSWORD,
    },
    packageManager: 'yarn',
    executableName: 'MyProject',
}
```

(**note:** this config is actually within a `forge.config.js`, but I've verified that electron-forge is passing this config down to packager since the other elements of the config make it into the package)

### Additional Information

I originally reported electron/electron-notarize#90 thinking this may have been a problem with `electron-notarize`, but after a lockfile maintenance upgrade by Renovate I discovered that upgrading `electron-packager` caused the problem I was having, so I assume something went wrong passing the configuration down to notarize..

**Comment by malept** [comment]
Thanks for filing an issue! In order to help you with your problem, we're going to need more information about it. In particular:

* Console output when you run electron-packager with the environment variable `DEBUG=electron-packager,electron-notarize` _(instructions for [Windows](https://github.com/visionmedia/debug#windows-command-prompt-notes) and [non-Windows](https://en.wikipedia.org/wiki/Environment_variable#Unix))_. Please include the stack trace if one exists.
