### ISSUE TITLE
`ignore` regexps ignored for production modules

### ISSUE THREAD

**Issue by starpit** [electron/electron-packager#1330]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

* **Electron Packager Version:**
  * 15.4.0
* **Electron Version:**
  * 16.0.4
* **Operating System:**
  * any
* **Last Known Working Electron Packager version:**:
  * n/a

### Expected Behavior

`ignore` option should allow me to filter out even production node modules.

### Actual Behavior

Because the `copy-filter` routine has this logic: https://github.com/electron/electron-packager/blob/main/src/copy-filter.js#L93-L99

therefore any path that satisfies `prune.isModule()` will completely ignore the `filterFunc` logic.

**Comment by malept** [comment]
This is by design. If you want to do this yourself, you can disable pruning by Packager and invoke the pruner in your custom ignore function.

**Comment by starpit** [comment]
I see, then it might be useful to clarify this in the api documentation? Which currently has:

> One or more additional [regular expression](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions) patterns

i'm assuming that you meant to imply your comment with the word "additional?" Otherwise, it is not clear. In particular, the api doc names several classes of filepaths that are always ignored, but does not specify which filepaths are always included (which seems to be "production modules in your package.json"?)

Thanks!
