### ISSUE TITLE
Is the handling of the icon file wrong?

### ISSUE THREAD

**Issue by cangSDARM** [electron/electron-packager#1334]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

if I set icon without ext:
![image](https://user-images.githubusercontent.com/20441896/154908549-d62337cd-0506-4e9a-aafa-e932a12e4a19.png)

According to [the logic in the source code](https://github.com/electron/electron-packager/blob/120f5b20123be22d9fb03157c3744e181b214a03/src/platform.js#L146), the result will be like this:
![image](https://user-images.githubusercontent.com/20441896/154908634-0214e996-eda9-4582-94be-6711af62baed.png)

Clearly the result is missing a dot, between filename and ext.

Maybe:
```js
let iconFilename = this.opts.icon
const ext = path.extname(iconFilename)
if (ext !== targetExt) {
      // make sure the dot exist
      iconFilename = iconFilename.endsWith('.') ? iconFilename : iconFilename + '.'
      iconFilename = path.join(path.dirname(iconFilename), path.basename(iconFilename, ext) + targetExt)
}
```

**Comment by jordanbtucker** [comment]
There are only two locations where `normalizeIconExtension` is called. In [mac.js](https://github.com/electron/electron-packager/blob/120f5b20123be22d9fb03157c3744e181b214a03/src/mac.js#L317) and [win32.js](https://github.com/electron/electron-packager/blob/ebcbd439ff3e0f6f92fa880ff28a8670a9bcf2ab/src/win32.js#L72). In both instances they include the dot in the extension.

So `normalizeIconExtension` would only work incorrectly if a dotless extension was provided as the argument to `targetExt`.

On Windows, your icon path should be normalized to `src/assets/icons/app/icon.ico`. Is that not happening?

**Comment by cangSDARM** [comment]
Should not. Icons on decks are not displayed correctly

**Comment by cangSDARM** [comment]
Oh I found it. An icon option is passed when creatingWindow. It should be this one that overwrites the icon
