### ISSUE TITLE
create post install scripts for rpm

### ISSUE THREAD

**Issue by fangjiataigao** [electron/electron-packager#1336]
### Preflight Checklist

* [ ] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Comment by malept** [comment]
This is out of scope, see [`electron-installer-redhat`](https://github.com/electron-userland/electron-installer-redhat).
