### ISSUE TITLE
Electron package build is failing after the latest release [15.5.2]

### ISSUE THREAD

**Issue by Karangoyal25892** [electron/electron-packager#1404]
Issue: Common.js is not imported in the cli.js which is breaking the build. Refer to the screenshot for the issue.
![image](https://user-images.githubusercontent.com/34648979/186111388-280ddb32-ba5d-4426-a5c6-3de718ce7ee7.png)

Fix: Info is not imported in the CLI file. Refer to the [link](https://github.com/electron/electron-packager/pull/1405) or the screenshot for the fix. 

![image](https://user-images.githubusercontent.com/34648979/186117765-58c6aecf-fc1b-4fc0-ac9e-e21b9a921870.png)

Fix PR: https://github.com/electron/electron-packager/pull/1405

**Comment by ioniall** [comment]
Looks like is from the commit ee600a1b15f5f2d4d097a71e682fbc2d97c628d3

The import { common... should probably have been import { info... and the matching common.info( logs be info( logs.

**Comment by Karangoyal25892** [comment]
> Looks like is from the commit [ee600a1](https://github.com/electron/electron-packager/commit/ee600a1b15f5f2d4d097a71e682fbc2d97c628d3)
> 
> The `import { common...` should probably have been `import { info...` and the matching `common.info(` logs be `info(` logs.

The Pull request is already raised with these changes
https://github.com/electron/electron-packager/pull/1405
