### ISSUE TITLE
EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '/private/tmp/electron-packager/darwin-x64-template/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'

### ISSUE THREAD

**Issue by SouravSanganeria26** [electron/electron-packager#1442]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

Electron Packager 15.5.2
Node v18.8.0
Host Operating system: darwin 21.4.0 (x64)

Electron version: v11.5.0

Last Known Working Electron Packager version: v13

Expected Behavior
Build should complete

Actual Behavior
Giving the following error: 
EEXIST: file already exists, symlink 'Versions/Current/Electron Framework' -> '/private/tmp/electron-packager/darwin-x64-template/Electron.app/Contents/Frameworks/Electron Framework.framework/Electron Framework'

**Comment by erickzhao** [comment]
@SouravSanganeria26 a repro would help us debug here.

**Comment by MarshallOfSound** [comment]
This is fixed in packager v17.1.1

Ref: https://github.com/electron/electron-packager/commit/745d28602b47a4e85a6878fd9a5f69130e55dce4

**Comment by SouravSanganeria26** [comment]
With packager v17.1.1, I get this error:

ENOTEMPTY: directory not empty, rename '/var/folders/2y/f_mvtf4x585d2900q1s2h5j00000gn/T/electron-packager/darwin-x64/<application-name>-0e3zrz' -> 'mac-application/<application-name>'
