### ISSUE TITLE
asar.unpack not working with glob syntax

### ISSUE THREAD

**Issue by tripower** [electron/electron-packager#1459]
Electron v18
Electron Packager v15.4.0

at the moment I have in package. json this syntax
  "package": "electron-packager . xxxx --asar.unpack=\"{package.json}\" 
but so all package.json files will be unpacked (my from root and all node modules) and I want only "my" one from the root
and my test with this pattern
/package.json => NOK
/{,!(node_modules)/**/}package.json => NOK
because so no file will be unpacked???

a bug? 
or wrong pattern?

thx for help

greetings
Klaus

**Comment by MarshallOfSound** [comment]
> or wrong pattern?

glob `{}` syntax doesn't work with a single item in the `{}`.  E.g. `{a}` won't match, but `{a,b}` would match.  If you write the right glob pattern it will work

**Comment by tripower** [comment]
i have more items inside the {}
but removed to set the focus for the not working one

so why the pattern below not work?
should be glob specific

**Comment by tripower** [comment]
that is with all inside
--asar.unpack=\"{**/jquery/**/*,**/node_modules/@json-editor/**/*,**/node_modules/dialog/**/*,**/jar/**/*,**/node_modules/java/**/*,**/jar/**/*,**/node_modules/winston/**/*,**/node_modules/lodash/**/*,**/node_modules/async/**/*,**/node_modules/path/**/*,**/node_modules/fs/**/*,**/jre/**/*,**/wacom/**/*,logback.xml,package.json}\"
