### ISSUE TITLE
Cannot output in the same directory its inputting

### ISSUE THREAD

**Issue by adminy** [electron/electron-packager#1460]
### Preflight Checklist

* [x] I have read the [contribution documentation](https://github.com/electron/electron-packager/blob/main/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [code of conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project follows, as appropriate.
* [x] I have searched the issue tracker for a bug that matches the one I want to file, without success.

### Issue Details

Electron Packager does not output in the same directory it takes its input.

Host Operating system: 

* **Electron Packager Version:**
  *   17.1.1
* **Electron Version:**
  *  21.3.0
* **Operating System:**
  *  darwin 22.1.0 (arm64)
* **Node Version:**
  * Node v18.9.0

### Expected Behavior

Generate output in the same folder as the input
```
Packaging app for platform darwin arm64 using electron v21.3.3
````
and in package.json the main can be: `"main": "./out/main/index.js",`

### Actual Behavior

```
Packaging app for platform darwin arm64 using electron v21.3.3
The main entry point to your app was not found. Make sure "out/main/index.js" exists and does not get ignored by your ignore option
```

### To Reproduce

```bash
yarn create @quick-start/electron my-app --template react # No to all
cd my-app
yarn
yarn build
npx electron-packager . --out ./out
```

But you get:
Packaging app for platform darwin arm64 using electron v21.3.3
The main entry point to your app was not found. Make sure "out/main/index.js" exists and does not get ignored by your ignore option

**Comment by erickzhao** [comment]
If you're using a template based on Electron Builder, I don't think you should be using Electron Packager to package your app. You should probably just use Builder directly instead.

**Comment by adminy** [comment]
The bug isn't in which template I'm using though ... Its in the --out flag. and the ignore not working.

**Comment by adminy** [comment]
Specifying --out in the folder of the input should be allowed, yet its ignoring it
>`npx electron-packager . --asar --out out`
Results in:
`The main entry point to your app was not found. Make sure "out/main/index.js" exists and does not get ignored by your ignore option`
