### ISSUE TITLE
`appIcon` option does nothing

### ISSUE THREAD

**Issue by gregcotten** [electron/electron-packager#1462]
I haven't had a moment to check with Windows yet, but I've reached my wit's end trying to get `electron-forge package` to use the icon path I provided.

I've tried setting my forge config file `packagerConfig:appIcon` as an absolute path (with and without the .icns file extension in the path) a relative path from the directory `electron-forge package` is called from (with and without the .icns file extension in the path) and then tried doing both of those again instead with a .png (with and without the .png extension in the path).

The packaged app always has an `electron.icns` file in the Resources folder and the Info.plist `CFBundleIconFile` is always set to electron.icns

Does anyone have any ideas?!?! I am using "vanilla" packaging without webpack if that is relevant.

```
Electron Packager 17.1.1
Node v19.1.0
Host Operating system: darwin 22.1.0 (arm64)
```

**Comment by malept** [comment]
Perhaps because it's called `icon` and not `appIcon`? Or is that a typo in the issue?

**Comment by gregcotten** [comment]
> Perhaps because it's called `icon` and not `appIcon`? Or is that a typo in the issue?

🤦‍♂️
